// Generated by scripts/sync-ios-poi-examples.mjs. Do not edit.
// Source: Storybook POI fixtures and taxonomy 10.12.0 projection.
import Foundation

enum POIExampleData {
    static let json = #"""
[
  {
    "id": "restaurant",
    "title": "Restaurant",
    "poi": {
      "id": "il-forno",
      "name": "Il Forno",
      "floorId": "1",
      "floorLabel": "Current floor",
      "buildingLabel": "Building A",
      "availability": "open",
      "availabilityLabel": "Open",
      "description": "Wood-fired Neapolitan pizza & handmade pasta in a lively open kitchen.",
      "media": [],
      "actions": [
        "navigate",
        "share",
        "favourite",
        "bookmark"
      ]
    },
    "details": {
      "travelEstimate": {
        "durationSeconds": 120,
        "durationLabel": "2 min",
        "distanceMetres": 120,
        "distanceLabel": "120 m"
      },
      "supplementaryActions": [
        {
          "action": "book",
          "label": "Book",
          "systemImage": "calendar.badge.checkmark"
        }
      ],
      "groups": [
        {
          "id": "Cuisines",
          "heading": "Cuisines",
          "items": [
            {
              "id": "cuisines:Italian",
              "label": "Italian"
            },
            {
              "id": "cuisines:Pizza",
              "label": "Pizza"
            },
            {
              "id": "cuisines:Mediterranean",
              "label": "Mediterranean"
            }
          ]
        },
        {
          "id": "Dietary Options",
          "heading": "Dietary Options",
          "items": [
            {
              "id": "dietaryOptions:Vegetarian",
              "label": "Vegetarian"
            },
            {
              "id": "dietaryOptions:Vegan",
              "label": "Vegan"
            },
            {
              "id": "dietaryOptions:Gluten-Free",
              "label": "Gluten-Free"
            }
          ]
        },
        {
          "id": "Service Options",
          "heading": "Service Options",
          "items": [
            {
              "id": "serviceOptions:Dine-in",
              "label": "Dine-in",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/service-options/dine-in.png",
              "iconMonochrome": true
            }
          ]
        },
        {
          "id": "Accessibility",
          "heading": "Accessibility",
          "items": [
            {
              "id": "isWheelchairAccessible:true",
              "label": "Wheelchair Friendly",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/is-wheelchair-accessible.png",
              "iconMonochrome": true
            },
            {
              "id": "hasHearingLoop:true",
              "label": "Hearing Loop",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-hearing-loop.png",
              "iconMonochrome": true
            },
            {
              "id": "hasVisualAids:true",
              "label": "Visual Aids",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-visual-aids.png",
              "iconMonochrome": true
            },
            {
              "id": "isAutismFriendly:true",
              "label": "Autism Friendly",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/is-autism-friendly.png",
              "iconMonochrome": true
            },
            {
              "id": "hasAssistance:true",
              "label": "Assistance Available",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-assistance.png",
              "iconMonochrome": true
            }
          ]
        },
        {
          "id": "Amenities",
          "heading": "Amenities",
          "items": [
            {
              "id": "hasWifi:true",
              "label": "WiFi",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-wifi.png",
              "iconMonochrome": true
            },
            {
              "id": "hasRestrooms:true",
              "label": "Restrooms",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-restrooms.png",
              "iconMonochrome": true
            },
            {
              "id": "hasOutdoorSeating:true",
              "label": "Outdoor Seating",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-outdoor-seating.png",
              "iconMonochrome": true
            },
            {
              "id": "hasPlayArea:true",
              "label": "Play Area",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-play-area.png",
              "iconMonochrome": true
            },
            {
              "id": "hasAlcoholService:true",
              "label": "Alcohol Service",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-alcohol-service.png",
              "iconMonochrome": true
            }
          ]
        },
        {
          "id": "Good to Know",
          "heading": "Good to Know",
          "items": [
            {
              "id": "isFamilyFriendly:true",
              "label": "Family Friendly",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/is-family-friendly.png",
              "iconMonochrome": true
            },
            {
              "id": "isPetFriendly:true",
              "label": "Pet Friendly",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/is-pet-friendly.png",
              "iconMonochrome": true
            }
          ]
        },
        {
          "id": "Dress Code",
          "heading": "Dress Code",
          "items": [
            {
              "id": "dressCodes:smart-casual",
              "label": "Smart Casual"
            }
          ]
        },
        {
          "id": "Age Restriction",
          "heading": "Age Restriction",
          "items": [
            {
              "id": "ageRestriction:18+",
              "label": "18+"
            }
          ]
        },
        {
          "id": "Payment Methods",
          "heading": "Payment Methods",
          "items": [
            {
              "id": "paymentMethods:Cash",
              "label": "Cash",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/cash.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Credit",
              "label": "Credit/Debit",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/credit.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Google Pay",
              "label": "Google Pay",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/google-pay.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Apple Pay",
              "label": "Apple Pay",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/apple-pay.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Contactless",
              "label": "Contactless",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/contactless.png",
              "iconMonochrome": true
            }
          ]
        }
      ],
      "summary": [
        {
          "id": "rating",
          "kind": "rating",
          "label": "Rating",
          "value": "4.7 / 5",
          "detail": "32 reviews",
          "systemImage": "star"
        },
        {
          "id": "priceRange",
          "kind": "price",
          "label": "Price Range",
          "value": "3 of 4",
          "priceLevel": 3,
          "tone": "neutral"
        },
        {
          "id": "isWheelchairAccessible",
          "kind": "property",
          "label": "Wheelchair Accessible",
          "value": "Wheelchair Friendly",
          "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/is-wheelchair-accessible.png",
          "iconMonochrome": true,
          "tone": "neutral"
        }
      ],
      "issues": [],
      "openingHours": {
        "label": "Opening hours",
        "summary": "Open · Closes 12:30 pm",
        "rows": [
          {
            "id": "weekdays",
            "day": "Monday–Friday",
            "hours": "8:00 am–12:30 pm"
          },
          {
            "id": "saturday",
            "day": "Saturday",
            "hours": "9:00 am–12:30 pm"
          },
          {
            "id": "sunday",
            "day": "Sunday",
            "hours": "Closed"
          }
        ],
        "note": "Illustrative venue-local hours; not a live opening-status calculation."
      },
      "description": {
        "preview": "Family-run since 1998, Il Forno serves Naples-style pizza from a wood-fired oven and pasta made fresh daily.",
        "full": "Family-run since 1998, Il Forno serves Naples-style pizza from a wood-fired oven and pasta made fresh daily. The terrace seats overlook the atrium, and the open kitchen is the heart of the room. Weekend evenings are lively — booking recommended."
      },
      "tags": [
        {
          "id": "pizza",
          "label": "#pizza"
        },
        {
          "id": "italian",
          "label": "#italian"
        },
        {
          "id": "patio",
          "label": "#patio"
        }
      ]
    }
  },
  {
    "id": "retail",
    "title": "Retail",
    "poi": {
      "id": "aria-and-co",
      "name": "Aria & Co.",
      "floorId": "1",
      "floorLabel": "Current floor",
      "buildingLabel": "Building A",
      "availability": "open",
      "availabilityLabel": "Open",
      "description": "Flagship fashion & lifestyle department store across three floors.",
      "media": [],
      "actions": [
        "navigate",
        "share",
        "favourite",
        "bookmark"
      ]
    },
    "details": {
      "travelEstimate": {
        "durationSeconds": 120,
        "durationLabel": "2 min",
        "distanceMetres": 120,
        "distanceLabel": "120 m"
      },
      "supplementaryActions": [
        {
          "action": "call",
          "label": "Call",
          "systemImage": "phone"
        }
      ],
      "groups": [
        {
          "id": "Product Types",
          "heading": "Product Types",
          "items": [
            {
              "id": "productTypes:Womens Clothing",
              "label": "Womens Clothing"
            },
            {
              "id": "productTypes:Mens Clothing",
              "label": "Mens Clothing"
            },
            {
              "id": "productTypes:Accessories",
              "label": "Accessories"
            },
            {
              "id": "productTypes:Beauty and Cosmetics",
              "label": "Beauty and Cosmetics"
            },
            {
              "id": "productTypes:Footwear",
              "label": "Footwear"
            },
            {
              "id": "productTypes:Home Decor",
              "label": "Home Decor"
            }
          ]
        },
        {
          "id": "Accessibility",
          "heading": "Accessibility",
          "items": [
            {
              "id": "isWheelchairAccessible:true",
              "label": "Wheelchair Friendly",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/is-wheelchair-accessible.png",
              "iconMonochrome": true
            },
            {
              "id": "hasAssistance:true",
              "label": "Assistance Available",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-assistance.png",
              "iconMonochrome": true
            }
          ]
        },
        {
          "id": "Amenities",
          "heading": "Amenities",
          "items": [
            {
              "id": "hasRestrooms:true",
              "label": "Restrooms",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-restrooms.png",
              "iconMonochrome": true
            },
            {
              "id": "hasChangingFacilities:true",
              "label": "Changing Facilities",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-changing-facilities.png",
              "iconMonochrome": true
            }
          ]
        },
        {
          "id": "Payment Methods",
          "heading": "Payment Methods",
          "items": [
            {
              "id": "paymentMethods:Cash",
              "label": "Cash",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/cash.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Credit",
              "label": "Credit/Debit",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/credit.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Mobile",
              "label": "Mobile",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/mobile.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Contactless",
              "label": "Contactless",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/contactless.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Apple Pay",
              "label": "Apple Pay",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/apple-pay.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Google Pay",
              "label": "Google Pay",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/google-pay.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Samsung Pay",
              "label": "Samsung Pay",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/samsung-pay.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Store Card",
              "label": "Store Card",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/store-card.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Gift Card",
              "label": "Gift Card",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/gift-card.png",
              "iconMonochrome": true
            }
          ]
        }
      ],
      "summary": [
        {
          "id": "rating",
          "kind": "rating",
          "label": "Rating",
          "value": "4.7 / 5",
          "detail": "32 reviews",
          "systemImage": "star"
        },
        {
          "id": "isWheelchairAccessible",
          "kind": "property",
          "label": "Wheelchair Accessible",
          "value": "Wheelchair Friendly",
          "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/is-wheelchair-accessible.png",
          "iconMonochrome": true,
          "tone": "neutral"
        },
        {
          "id": "crowdLevel",
          "kind": "property",
          "label": "Crowd Level",
          "value": "Packed",
          "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/crowd-level.png",
          "iconMonochrome": true,
          "tone": "danger",
          "detail": "25 min wait"
        }
      ],
      "issues": [],
      "openingHours": {
        "label": "Opening hours",
        "summary": "Open · Closes 12:30 pm",
        "rows": [
          {
            "id": "weekdays",
            "day": "Monday–Friday",
            "hours": "8:00 am–12:30 pm"
          },
          {
            "id": "saturday",
            "day": "Saturday",
            "hours": "9:00 am–12:30 pm"
          },
          {
            "id": "sunday",
            "day": "Sunday",
            "hours": "Closed"
          }
        ],
        "note": "Illustrative venue-local hours; not a live opening-status calculation."
      },
      "description": {
        "preview": "Three floors of curated fashion, beauty and homeware, with a rooftop café and a dedicated personal-shopping suite on Level 3.",
        "full": "Three floors of curated fashion, beauty and homeware, with a rooftop café and a dedicated personal-shopping suite on Level 3. Seasonal collections rotate monthly and members get early access to sale previews."
      },
      "tags": [
        {
          "id": "fashion",
          "label": "#fashion"
        },
        {
          "id": "lifestyle",
          "label": "#lifestyle"
        }
      ]
    }
  },
  {
    "id": "fitness",
    "title": "Fitness",
    "poi": {
      "id": "peak-performance",
      "name": "Peak Performance",
      "floorId": "1",
      "floorLabel": "Current floor",
      "buildingLabel": "Building A",
      "availability": "open",
      "availabilityLabel": "Open",
      "description": "A high-intensity fitness studio offering group classes and open gym access.",
      "media": [],
      "actions": [
        "navigate",
        "share",
        "favourite",
        "bookmark"
      ]
    },
    "details": {
      "travelEstimate": {
        "durationSeconds": 120,
        "durationLabel": "2 min",
        "distanceMetres": 120,
        "distanceLabel": "120 m"
      },
      "supplementaryActions": [
        {
          "action": "book",
          "label": "Book",
          "systemImage": "calendar.badge.checkmark"
        }
      ],
      "groups": [
        {
          "id": "Sport Types",
          "heading": "Sport Types",
          "items": [
            {
              "id": "sportTypes:Aerobics",
              "label": "Aerobics"
            },
            {
              "id": "sportTypes:Athletics",
              "label": "Athletics"
            }
          ]
        },
        {
          "id": "Accessibility",
          "heading": "Accessibility",
          "items": [
            {
              "id": "isWheelchairAccessible:true",
              "label": "Wheelchair Friendly",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/is-wheelchair-accessible.png",
              "iconMonochrome": true
            },
            {
              "id": "hasAssistance:true",
              "label": "Assistance Available",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-assistance.png",
              "iconMonochrome": true
            }
          ]
        },
        {
          "id": "Amenities",
          "heading": "Amenities",
          "items": [
            {
              "id": "hasWifi:true",
              "label": "WiFi",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-wifi.png",
              "iconMonochrome": true
            },
            {
              "id": "hasChargingAvailable:true",
              "label": "Chargers",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-charging-available.png",
              "iconMonochrome": true
            },
            {
              "id": "hasRestrooms:true",
              "label": "Restrooms",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-restrooms.png",
              "iconMonochrome": true
            },
            {
              "id": "hasLockers:true",
              "label": "Locker Room",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-lockers.png",
              "iconMonochrome": true
            },
            {
              "id": "hasChangingFacilities:true",
              "label": "Changing Facilities",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-changing-facilities.png",
              "iconMonochrome": true
            }
          ]
        },
        {
          "id": "Good to Know",
          "heading": "Good to Know",
          "items": [
            {
              "id": "isFamilyFriendly:true",
              "label": "Family Friendly",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/is-family-friendly.png",
              "iconMonochrome": true
            }
          ]
        },
        {
          "id": "Dress Code",
          "heading": "Dress Code",
          "items": [
            {
              "id": "dressCodes:smart-casual",
              "label": "Smart Casual"
            }
          ]
        },
        {
          "id": "Age Restriction",
          "heading": "Age Restriction",
          "items": [
            {
              "id": "ageRestriction:18+",
              "label": "18+"
            }
          ]
        },
        {
          "id": "Gender Designation",
          "heading": "Gender Designation",
          "items": [
            {
              "id": "genderDesignation:all-gender",
              "label": "All-Gender"
            }
          ]
        },
        {
          "id": "Language Support",
          "heading": "Language Support",
          "items": [
            {
              "id": "languageSupport:English",
              "label": "English"
            },
            {
              "id": "languageSupport:Spanish",
              "label": "Spanish"
            },
            {
              "id": "languageSupport:French",
              "label": "French"
            }
          ]
        },
        {
          "id": "Access Restrictions",
          "heading": "Access Restrictions",
          "items": [
            {
              "id": "accessRestrictions:booking-required",
              "label": "Booking Required"
            }
          ]
        },
        {
          "id": "Payment Methods",
          "heading": "Payment Methods",
          "items": [
            {
              "id": "paymentMethods:Cash",
              "label": "Cash",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/cash.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Credit",
              "label": "Credit/Debit",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/credit.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Mobile",
              "label": "Mobile",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/mobile.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Contactless",
              "label": "Contactless",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/contactless.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Apple Pay",
              "label": "Apple Pay",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/apple-pay.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Google Pay",
              "label": "Google Pay",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/google-pay.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Samsung Pay",
              "label": "Samsung Pay",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/samsung-pay.png",
              "iconMonochrome": true
            }
          ]
        }
      ],
      "summary": [
        {
          "id": "rating",
          "kind": "rating",
          "label": "Rating",
          "value": "4.7 / 5",
          "detail": "32 reviews",
          "systemImage": "star"
        },
        {
          "id": "priceRange",
          "kind": "price",
          "label": "Price Range",
          "value": "3 of 4",
          "priceLevel": 3,
          "tone": "neutral"
        },
        {
          "id": "isWheelchairAccessible",
          "kind": "property",
          "label": "Wheelchair Accessible",
          "value": "Wheelchair Friendly",
          "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/is-wheelchair-accessible.png",
          "iconMonochrome": true,
          "tone": "neutral"
        }
      ],
      "issues": [],
      "openingHours": {
        "label": "Opening hours",
        "summary": "Open · Closes 12:30 pm",
        "rows": [
          {
            "id": "weekdays",
            "day": "Monday–Friday",
            "hours": "8:00 am–12:30 pm"
          },
          {
            "id": "saturday",
            "day": "Saturday",
            "hours": "9:00 am–12:30 pm"
          },
          {
            "id": "sunday",
            "day": "Sunday",
            "hours": "Closed"
          }
        ],
        "note": "Illustrative venue-local hours; not a live opening-status calculation."
      },
      "description": {
        "preview": "Peak Performance Studio provides cardio and weightlifting equipment alongside daily instructor-led aerobics and athletics classes.",
        "full": "Peak Performance Studio provides cardio and weightlifting equipment alongside daily instructor-led aerobics and athletics classes. Lockers and showers are available on-site for all members."
      },
      "tags": [
        {
          "id": "fitness",
          "label": "#fitness"
        },
        {
          "id": "gym",
          "label": "#gym"
        }
      ]
    }
  },
  {
    "id": "entrance",
    "title": "Entrance",
    "poi": {
      "id": "terminal-1",
      "name": "Terminal 1 Main Entrance",
      "floorId": "1",
      "floorLabel": "Current floor",
      "buildingLabel": "Building A",
      "availability": "open",
      "availabilityLabel": "Open",
      "media": [],
      "actions": [
        "navigate",
        "share",
        "favourite",
        "bookmark"
      ]
    },
    "details": {
      "travelEstimate": {
        "durationSeconds": 120,
        "durationLabel": "2 min",
        "distanceMetres": 120,
        "distanceLabel": "120 m"
      },
      "groups": [
        {
          "id": "Accessibility",
          "heading": "Accessibility",
          "items": [
            {
              "id": "isWheelchairAccessible:true",
              "label": "Wheelchair Friendly",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/is-wheelchair-accessible.png",
              "iconMonochrome": true
            },
            {
              "id": "hasHearingLoop:true",
              "label": "Hearing Loop",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-hearing-loop.png",
              "iconMonochrome": true
            },
            {
              "id": "hasVisualAids:true",
              "label": "Visual Aids",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-visual-aids.png",
              "iconMonochrome": true
            },
            {
              "id": "isAutismFriendly:true",
              "label": "Autism Friendly",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/is-autism-friendly.png",
              "iconMonochrome": true
            },
            {
              "id": "hasAssistance:true",
              "label": "Assistance Available",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-assistance.png",
              "iconMonochrome": true
            }
          ]
        },
        {
          "id": "Amenities",
          "heading": "Amenities",
          "items": [
            {
              "id": "hasWifi:true",
              "label": "WiFi",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-wifi.png",
              "iconMonochrome": true
            },
            {
              "id": "hasChargingAvailable:true",
              "label": "Chargers",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-charging-available.png",
              "iconMonochrome": true
            },
            {
              "id": "hasRestrooms:true",
              "label": "Restrooms",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-restrooms.png",
              "iconMonochrome": true
            },
            {
              "id": "hasLuggageStorage:true",
              "label": "Luggage Storage",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-luggage-storage.png",
              "iconMonochrome": true
            },
            {
              "id": "hasSecurityStaff:true",
              "label": "Security Staff",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-security-staff.png",
              "iconMonochrome": true
            }
          ]
        },
        {
          "id": "Language Support",
          "heading": "Language Support",
          "items": [
            {
              "id": "languageSupport:English",
              "label": "English"
            },
            {
              "id": "languageSupport:Spanish",
              "label": "Spanish"
            },
            {
              "id": "languageSupport:French",
              "label": "French"
            }
          ]
        },
        {
          "id": "Access Programs",
          "heading": "Access Programs",
          "items": [
            {
              "id": "accessPrograms:tsa-precheck",
              "label": "TSA PreCheck"
            },
            {
              "id": "accessPrograms:clear",
              "label": "CLEAR"
            },
            {
              "id": "accessPrograms:global-entry",
              "label": "Global Entry"
            }
          ]
        }
      ],
      "summary": [
        {
          "id": "isWheelchairAccessible",
          "kind": "property",
          "label": "Wheelchair Accessible",
          "value": "Wheelchair Friendly",
          "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/is-wheelchair-accessible.png",
          "iconMonochrome": true,
          "tone": "neutral"
        }
      ],
      "issues": [],
      "openingHours": {
        "label": "Opening hours",
        "summary": "Open · Closes 12:30 pm",
        "rows": [
          {
            "id": "weekdays",
            "day": "Monday–Friday",
            "hours": "8:00 am–12:30 pm"
          },
          {
            "id": "saturday",
            "day": "Saturday",
            "hours": "9:00 am–12:30 pm"
          },
          {
            "id": "sunday",
            "day": "Sunday",
            "hours": "Closed"
          }
        ],
        "note": "Illustrative venue-local hours; not a live opening-status calculation."
      },
      "tags": [],
      "supplementaryActions": []
    }
  },
  {
    "id": "parking",
    "title": "Parking",
    "poi": {
      "id": "north-deck",
      "name": "North Deck Parking",
      "floorId": "1",
      "floorLabel": "Current floor",
      "buildingLabel": "Building A",
      "availability": "open",
      "availabilityLabel": "Open",
      "media": [],
      "actions": [
        "navigate",
        "share",
        "favourite",
        "bookmark"
      ]
    },
    "details": {
      "travelEstimate": {
        "durationSeconds": 120,
        "durationLabel": "2 min",
        "distanceMetres": 120,
        "distanceLabel": "120 m"
      },
      "groups": [
        {
          "id": "Accessibility",
          "heading": "Accessibility",
          "items": [
            {
              "id": "isWheelchairAccessible:true",
              "label": "Wheelchair Friendly",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/is-wheelchair-accessible.png",
              "iconMonochrome": true
            }
          ]
        },
        {
          "id": "Parking Types",
          "heading": "Parking Types",
          "items": [
            {
              "id": "parkingTypes:Self-Park",
              "label": "Self-Park"
            },
            {
              "id": "parkingTypes:Valet",
              "label": "Valet"
            },
            {
              "id": "parkingTypes:EV Charging",
              "label": "EV Charging"
            }
          ]
        },
        {
          "id": "Payment Methods",
          "heading": "Payment Methods",
          "items": [
            {
              "id": "paymentMethods:Credit",
              "label": "Credit/Debit",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/credit.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Contactless",
              "label": "Contactless",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/contactless.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Apple Pay",
              "label": "Apple Pay",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/apple-pay.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Google Pay",
              "label": "Google Pay",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/google-pay.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Samsung Pay",
              "label": "Samsung Pay",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/samsung-pay.png",
              "iconMonochrome": true
            }
          ]
        }
      ],
      "summary": [
        {
          "id": "isWheelchairAccessible",
          "kind": "property",
          "label": "Wheelchair Accessible",
          "value": "Wheelchair Friendly",
          "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/is-wheelchair-accessible.png",
          "iconMonochrome": true,
          "tone": "neutral"
        },
        {
          "id": "crowdLevel",
          "kind": "property",
          "label": "Crowd Level",
          "value": "Packed",
          "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/crowd-level.png",
          "iconMonochrome": true,
          "tone": "danger",
          "detail": "25 min wait"
        }
      ],
      "issues": [],
      "openingHours": {
        "label": "Opening hours",
        "summary": "Open · Closes 12:30 pm",
        "rows": [
          {
            "id": "weekdays",
            "day": "Monday–Friday",
            "hours": "8:00 am–12:30 pm"
          },
          {
            "id": "saturday",
            "day": "Saturday",
            "hours": "9:00 am–12:30 pm"
          },
          {
            "id": "sunday",
            "day": "Sunday",
            "hours": "Closed"
          }
        ],
        "note": "Illustrative venue-local hours; not a live opening-status calculation."
      },
      "tags": [],
      "supplementaryActions": []
    }
  },
  {
    "id": "full-fields",
    "title": "All properties",
    "poi": {
      "id": "il-forno",
      "name": "Il Forno",
      "floorId": "1",
      "floorLabel": "Current floor",
      "buildingLabel": "Building A",
      "availability": "open",
      "availabilityLabel": "Open",
      "description": "Wood-fired Neapolitan pizza & handmade pasta in a lively open kitchen.",
      "media": [],
      "actions": [
        "navigate",
        "share",
        "favourite",
        "bookmark"
      ]
    },
    "details": {
      "travelEstimate": {
        "durationSeconds": 120,
        "durationLabel": "2 min",
        "distanceMetres": 120,
        "distanceLabel": "120 m"
      },
      "supplementaryActions": [
        {
          "action": "book",
          "label": "Book",
          "systemImage": "calendar.badge.checkmark"
        }
      ],
      "groups": [
        {
          "id": "Cuisines",
          "heading": "Cuisines",
          "items": [
            {
              "id": "cuisines:Italian",
              "label": "Italian"
            },
            {
              "id": "cuisines:Pizza",
              "label": "Pizza"
            },
            {
              "id": "cuisines:Mediterranean",
              "label": "Mediterranean"
            }
          ]
        },
        {
          "id": "Dietary Options",
          "heading": "Dietary Options",
          "items": [
            {
              "id": "dietaryOptions:Vegetarian",
              "label": "Vegetarian"
            },
            {
              "id": "dietaryOptions:Vegan",
              "label": "Vegan"
            },
            {
              "id": "dietaryOptions:Gluten-Free",
              "label": "Gluten-Free"
            }
          ]
        },
        {
          "id": "Service Options",
          "heading": "Service Options",
          "items": [
            {
              "id": "serviceOptions:Dine-in",
              "label": "Dine-in",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/service-options/dine-in.png",
              "iconMonochrome": true
            }
          ]
        },
        {
          "id": "Product Types",
          "heading": "Product Types",
          "items": [
            {
              "id": "productTypes:Womens Clothing",
              "label": "Womens Clothing"
            },
            {
              "id": "productTypes:Mens Clothing",
              "label": "Mens Clothing"
            },
            {
              "id": "productTypes:Accessories",
              "label": "Accessories"
            },
            {
              "id": "productTypes:Beauty and Cosmetics",
              "label": "Beauty and Cosmetics"
            },
            {
              "id": "productTypes:Footwear",
              "label": "Footwear"
            },
            {
              "id": "productTypes:Home Decor",
              "label": "Home Decor"
            }
          ]
        },
        {
          "id": "Clinical Specialty",
          "heading": "Clinical Specialty",
          "items": [
            {
              "id": "clinicalSpecialty:Acupuncture",
              "label": "Acupuncture"
            },
            {
              "id": "clinicalSpecialty:Allergy and Immunology",
              "label": "Allergy and Immunology"
            },
            {
              "id": "clinicalSpecialty:Audiology",
              "label": "Audiology"
            }
          ]
        },
        {
          "id": "Sport Types",
          "heading": "Sport Types",
          "items": [
            {
              "id": "sportTypes:Aerobics",
              "label": "Aerobics"
            },
            {
              "id": "sportTypes:Athletics",
              "label": "Athletics"
            }
          ]
        },
        {
          "id": "Service Types",
          "heading": "Service Types",
          "items": [
            {
              "id": "serviceTypes:Barber and Hair Salon",
              "label": "Barber and Hair Salon"
            },
            {
              "id": "serviceTypes:Beauty and Spa Services",
              "label": "Beauty and Spa Services"
            }
          ]
        },
        {
          "id": "Accessibility",
          "heading": "Accessibility",
          "items": [
            {
              "id": "isWheelchairAccessible:true",
              "label": "Wheelchair Friendly",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/is-wheelchair-accessible.png",
              "iconMonochrome": true
            },
            {
              "id": "hasHearingLoop:true",
              "label": "Hearing Loop",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-hearing-loop.png",
              "iconMonochrome": true
            },
            {
              "id": "hasVisualAids:true",
              "label": "Visual Aids",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-visual-aids.png",
              "iconMonochrome": true
            },
            {
              "id": "isAutismFriendly:true",
              "label": "Autism Friendly",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/is-autism-friendly.png",
              "iconMonochrome": true
            },
            {
              "id": "hasAssistance:true",
              "label": "Assistance Available",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-assistance.png",
              "iconMonochrome": true
            }
          ]
        },
        {
          "id": "Amenities",
          "heading": "Amenities",
          "items": [
            {
              "id": "hasWifi:true",
              "label": "WiFi",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-wifi.png",
              "iconMonochrome": true
            },
            {
              "id": "hasChargingAvailable:true",
              "label": "Chargers",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-charging-available.png",
              "iconMonochrome": true
            },
            {
              "id": "hasRestrooms:true",
              "label": "Restrooms",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-restrooms.png",
              "iconMonochrome": true
            },
            {
              "id": "hasLockers:true",
              "label": "Locker Room",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-lockers.png",
              "iconMonochrome": true
            },
            {
              "id": "hasLuggageStorage:true",
              "label": "Luggage Storage",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-luggage-storage.png",
              "iconMonochrome": true
            },
            {
              "id": "hasChangingFacilities:true",
              "label": "Changing Facilities",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-changing-facilities.png",
              "iconMonochrome": true
            },
            {
              "id": "hasOutdoorSeating:true",
              "label": "Outdoor Seating",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-outdoor-seating.png",
              "iconMonochrome": true
            },
            {
              "id": "hasPlayArea:true",
              "label": "Play Area",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-play-area.png",
              "iconMonochrome": true
            },
            {
              "id": "hasSecurityStaff:true",
              "label": "Security Staff",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-security-staff.png",
              "iconMonochrome": true
            },
            {
              "id": "hasAlcoholService:true",
              "label": "Alcohol Service",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/has-alcohol-service.png",
              "iconMonochrome": true
            }
          ]
        },
        {
          "id": "Good to Know",
          "heading": "Good to Know",
          "items": [
            {
              "id": "isFamilyFriendly:true",
              "label": "Family Friendly",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/is-family-friendly.png",
              "iconMonochrome": true
            },
            {
              "id": "isPetFriendly:true",
              "label": "Pet Friendly",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/is-pet-friendly.png",
              "iconMonochrome": true
            }
          ]
        },
        {
          "id": "Dress Code",
          "heading": "Dress Code",
          "items": [
            {
              "id": "dressCodes:smart-casual",
              "label": "Smart Casual"
            }
          ]
        },
        {
          "id": "Age Restriction",
          "heading": "Age Restriction",
          "items": [
            {
              "id": "ageRestriction:18+",
              "label": "18+"
            }
          ]
        },
        {
          "id": "Gender Designation",
          "heading": "Gender Designation",
          "items": [
            {
              "id": "genderDesignation:all-gender",
              "label": "All-Gender"
            }
          ]
        },
        {
          "id": "Capacity",
          "heading": "Capacity",
          "items": [
            {
              "id": "capacity:80",
              "label": "80",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/capacity.png",
              "iconMonochrome": true
            }
          ]
        },
        {
          "id": "Language Support",
          "heading": "Language Support",
          "items": [
            {
              "id": "languageSupport:English",
              "label": "English"
            },
            {
              "id": "languageSupport:Spanish",
              "label": "Spanish"
            },
            {
              "id": "languageSupport:French",
              "label": "French"
            }
          ]
        },
        {
          "id": "Parking Types",
          "heading": "Parking Types",
          "items": [
            {
              "id": "parkingTypes:Self-Park",
              "label": "Self-Park"
            },
            {
              "id": "parkingTypes:Valet",
              "label": "Valet"
            },
            {
              "id": "parkingTypes:EV Charging",
              "label": "EV Charging"
            }
          ]
        },
        {
          "id": "Access Programs",
          "heading": "Access Programs",
          "items": [
            {
              "id": "accessPrograms:tsa-precheck",
              "label": "TSA PreCheck"
            },
            {
              "id": "accessPrograms:clear",
              "label": "CLEAR"
            },
            {
              "id": "accessPrograms:global-entry",
              "label": "Global Entry"
            }
          ]
        },
        {
          "id": "Access Restrictions",
          "heading": "Access Restrictions",
          "items": [
            {
              "id": "accessRestrictions:booking-required",
              "label": "Booking Required"
            }
          ]
        },
        {
          "id": "Payment Methods",
          "heading": "Payment Methods",
          "items": [
            {
              "id": "paymentMethods:Credit",
              "label": "Credit/Debit",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/credit.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Contactless",
              "label": "Contactless",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/contactless.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Apple Pay",
              "label": "Apple Pay",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/apple-pay.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Google Pay",
              "label": "Google Pay",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/google-pay.png",
              "iconMonochrome": true
            },
            {
              "id": "paymentMethods:Samsung Pay",
              "label": "Samsung Pay",
              "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/values/payment-methods/samsung-pay.png",
              "iconMonochrome": true
            }
          ]
        }
      ],
      "summary": [
        {
          "id": "priceRange",
          "kind": "price",
          "label": "Price Range",
          "value": "3 of 4",
          "priceLevel": 3,
          "tone": "neutral"
        },
        {
          "id": "isWheelchairAccessible",
          "kind": "property",
          "label": "Wheelchair Accessible",
          "value": "Wheelchair Friendly",
          "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/is-wheelchair-accessible.png",
          "iconMonochrome": true,
          "tone": "neutral"
        },
        {
          "id": "crowdLevel",
          "kind": "property",
          "label": "Crowd Level",
          "value": "Packed",
          "iconUrl": "https://mapscdn.pointr.tech/taxonomy/10.12.0/symbols/properties/crowd-level.png",
          "iconMonochrome": true,
          "tone": "danger",
          "detail": "25 min wait"
        }
      ],
      "issues": [],
      "openingHours": {
        "label": "Opening hours",
        "summary": "Open · Closes 12:30 pm",
        "rows": [
          {
            "id": "weekdays",
            "day": "Monday–Friday",
            "hours": "8:00 am–12:30 pm"
          },
          {
            "id": "saturday",
            "day": "Saturday",
            "hours": "9:00 am–12:30 pm"
          },
          {
            "id": "sunday",
            "day": "Sunday",
            "hours": "Closed"
          }
        ],
        "note": "Illustrative venue-local hours; not a live opening-status calculation."
      },
      "description": {
        "preview": "Family-run since 1998, Il Forno serves Naples-style pizza from a wood-fired oven and pasta made fresh daily.",
        "full": "Family-run since 1998, Il Forno serves Naples-style pizza from a wood-fired oven and pasta made fresh daily. The terrace seats overlook the atrium, and the open kitchen is the heart of the room. Weekend evenings are lively — booking recommended."
      },
      "tags": [
        {
          "id": "pizza",
          "label": "#pizza"
        },
        {
          "id": "italian",
          "label": "#italian"
        },
        {
          "id": "patio",
          "label": "#patio"
        }
      ]
    }
  }
]
"""#
}
