import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Bell,
  Building2,
  Bus,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Compass,
  Download,
  Edit,
  Home,
  Info,
  Lock,
  Map,
  MapPin,
  Menu,
  Minus,
  Navigation,
  Plus,
  QrCode,
  Route,
  ScanLine,
  Search,
  Settings,
  Trash2,
  Upload,
  User,
  Users,
  Wifi,
  X,
} from "lucide-react";

export const kozmosIconNames = [
  "activity",
  "alert-circle",
  "alert-triangle",
  "arrow-left",
  "arrow-right",
  "bell-01",
  "building-01",
  "bus",
  "calendar",
  "check",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "chevron-up",
  "clock",
  "compass-01",
  "download-01",
  "edit-01",
  "home-line",
  "info-circle",
  "lock-01",
  "map-01",
  "marker-pin-01",
  "menu-01",
  "minus",
  "navigation-pointer-01",
  "plus",
  "qr-code-01",
  "route",
  "scan",
  "search-md",
  "settings-01",
  "trash-01",
  "upload-01",
  "user-01",
  "users-01",
  "wifi",
  "x-close",
] as const;

export type KozmosIconName = (typeof kozmosIconNames)[number];

export interface KozmosIconDefinition {
  name: KozmosIconName;
  figmaName: string;
  figmaNodeId: string;
  category: string;
  description: string;
  component: LucideIcon;
}

export const kozmosIconDefinitions: readonly KozmosIconDefinition[] = [
  {
    name: "activity",
    figmaName: "activity",
    figmaNodeId: "1007:9735",
    category: "General",
    description: "Activity and status pulse.",
    component: Activity,
  },
  {
    name: "alert-circle",
    figmaName: "alert-circle",
    figmaNodeId: "1007:10316",
    category: "Alerts & feedback",
    description: "Circular warning or validation alert.",
    component: AlertCircle,
  },
  {
    name: "alert-triangle",
    figmaName: "alert-triangle",
    figmaNodeId: "1007:10328",
    category: "Alerts & feedback",
    description: "Triangular warning alert.",
    component: AlertTriangle,
  },
  {
    name: "arrow-left",
    figmaName: "arrow-left",
    figmaNodeId: "1007:9286",
    category: "Arrows",
    description: "Directional arrow left.",
    component: ArrowLeft,
  },
  {
    name: "arrow-right",
    figmaName: "arrow-right",
    figmaNodeId: "1007:9313",
    category: "Arrows",
    description: "Directional arrow right.",
    component: ArrowRight,
  },
  {
    name: "bell-01",
    figmaName: "bell-01",
    figmaNodeId: "1007:10340",
    category: "General",
    description: "Notification bell.",
    component: Bell,
  },
  {
    name: "building-01",
    figmaName: "building-01",
    figmaNodeId: "1007:9771",
    category: "General",
    description: "Building or venue.",
    component: Building2,
  },
  {
    name: "bus",
    figmaName: "bus",
    figmaNodeId: "1007:11761",
    category: "Maps & travel",
    description: "Bus transit mode.",
    component: Bus,
  },
  {
    name: "calendar",
    figmaName: "calendar",
    figmaNodeId: "1007:11518",
    category: "Time",
    description: "Calendar date picker.",
    component: Calendar,
  },
  {
    name: "check",
    figmaName: "check",
    figmaNodeId: "1007:9795",
    category: "General",
    description: "Confirmation check mark.",
    component: Check,
  },
  {
    name: "chevron-down",
    figmaName: "chevron-down",
    figmaNodeId: "1007:9364",
    category: "Arrows",
    description: "Chevron down.",
    component: ChevronDown,
  },
  {
    name: "chevron-left",
    figmaName: "chevron-left",
    figmaNodeId: "1007:9370",
    category: "Arrows",
    description: "Chevron left.",
    component: ChevronLeft,
  },
  {
    name: "chevron-right",
    figmaName: "chevron-right",
    figmaNodeId: "1007:9376",
    category: "Arrows",
    description: "Chevron right.",
    component: ChevronRight,
  },
  {
    name: "chevron-up",
    figmaName: "chevron-up",
    figmaNodeId: "1007:9388",
    category: "Arrows",
    description: "Chevron up.",
    component: ChevronUp,
  },
  {
    name: "clock",
    figmaName: "clock",
    figmaNodeId: "1007:11548",
    category: "Time",
    description: "Clock or time.",
    component: Clock,
  },
  {
    name: "compass-01",
    figmaName: "compass-01",
    figmaNodeId: "1007:11770",
    category: "Maps & travel",
    description: "Compass navigation.",
    component: Compass,
  },
  {
    name: "download-01",
    figmaName: "download-01",
    figmaNodeId: "1007:9873",
    category: "General",
    description: "Download action.",
    component: Download,
  },
  {
    name: "edit-01",
    figmaName: "edit-01",
    figmaNodeId: "1007:10179",
    category: "General",
    description: "Edit action.",
    component: Edit,
  },
  {
    name: "home-line",
    figmaName: "home-line",
    figmaNodeId: "1007:10275",
    category: "General",
    description: "Home navigation.",
    component: Home,
  },
  {
    name: "info-circle",
    figmaName: "info-circle",
    figmaNodeId: "1007:10281",
    category: "Alerts & feedback",
    description: "Informational message.",
    component: Info,
  },
  {
    name: "lock-01",
    figmaName: "lock-01",
    figmaNodeId: "1007:8883",
    category: "Security",
    description: "Locked or private state.",
    component: Lock,
  },
  {
    name: "map-01",
    figmaName: "map-01",
    figmaNodeId: "1007:11824",
    category: "Maps & travel",
    description: "Map view.",
    component: Map,
  },
  {
    name: "marker-pin-01",
    figmaName: "marker-pin-01",
    figmaNodeId: "1007:11833",
    category: "Maps & travel",
    description: "Map pin or destination marker.",
    component: MapPin,
  },
  {
    name: "menu-01",
    figmaName: "menu-01",
    figmaNodeId: "1007:10077",
    category: "General",
    description: "Navigation menu.",
    component: Menu,
  },
  {
    name: "minus",
    figmaName: "minus",
    figmaNodeId: "1007:10092",
    category: "General",
    description: "Remove, collapse, or decrement.",
    component: Minus,
  },
  {
    name: "navigation-pointer-01",
    figmaName: "navigation-pointer-01",
    figmaNodeId: "1007:11851",
    category: "Maps & travel",
    description: "Navigation pointer.",
    component: Navigation,
  },
  {
    name: "plus",
    figmaName: "plus",
    figmaNodeId: "1007:10119",
    category: "General",
    description: "Add or expand.",
    component: Plus,
  },
  {
    name: "qr-code-01",
    figmaName: "qr-code-01",
    figmaNodeId: "1007:9176",
    category: "Development",
    description: "QR code.",
    component: QrCode,
  },
  {
    name: "route",
    figmaName: "route",
    figmaNodeId: "1007:11875",
    category: "Maps & travel",
    description: "Route or path.",
    component: Route,
  },
  {
    name: "scan",
    figmaName: "scan",
    figmaNodeId: "1007:8919",
    category: "Security",
    description: "Scan frame.",
    component: ScanLine,
  },
  {
    name: "search-md",
    figmaName: "search-md",
    figmaNodeId: "1007:10140",
    category: "General",
    description: "Search action.",
    component: Search,
  },
  {
    name: "settings-01",
    figmaName: "settings-01",
    figmaNodeId: "1007:10149",
    category: "General",
    description: "Settings.",
    component: Settings,
  },
  {
    name: "trash-01",
    figmaName: "trash-01",
    figmaNodeId: "1007:9963",
    category: "General",
    description: "Delete action.",
    component: Trash2,
  },
  {
    name: "upload-01",
    figmaName: "upload-01",
    figmaNodeId: "1007:9975",
    category: "General",
    description: "Upload action.",
    component: Upload,
  },
  {
    name: "user-01",
    figmaName: "user-01",
    figmaNodeId: "1007:10494",
    category: "Users",
    description: "Single user.",
    component: User,
  },
  {
    name: "users-01",
    figmaName: "users-01",
    figmaNodeId: "1007:10566",
    category: "Users",
    description: "User group.",
    component: Users,
  },
  {
    name: "wifi",
    figmaName: "wifi",
    figmaNodeId: "1007:10913",
    category: "Media & devices",
    description: "Wireless connection.",
    component: Wifi,
  },
  {
    name: "x-close",
    figmaName: "x-close",
    figmaNodeId: "1007:9999",
    category: "General",
    description: "Close or dismiss.",
    component: X,
  },
];

export const kozmosIconRegistry = Object.fromEntries(
  kozmosIconDefinitions.map((icon) => [icon.name, icon.component]),
) as Record<KozmosIconName, LucideIcon>;

export const kozmosIconAliases = {
  add: "plus",
  back: "arrow-left",
  close: "x-close",
  delete: "trash-01",
  edit: "edit-01",
  home: "home-line",
  location: "marker-pin-01",
  "map-pin": "marker-pin-01",
  menu: "menu-01",
  next: "arrow-right",
  notifications: "bell-01",
  search: "search-md",
  settings: "settings-01",
  user: "user-01",
  users: "users-01",
  warning: "alert-triangle",
  x: "x-close",
} as const satisfies Record<string, KozmosIconName>;

export type KozmosIconAlias = keyof typeof kozmosIconAliases;
export type KozmosIconKey = KozmosIconName | KozmosIconAlias;

export function resolveIconName(name: KozmosIconKey): KozmosIconName {
  return kozmosIconAliases[name as KozmosIconAlias] ?? (name as KozmosIconName);
}

export function getIconComponent(name: KozmosIconKey): LucideIcon | undefined {
  return kozmosIconRegistry[resolveIconName(name)];
}

export function getIconDefinition(
  name: KozmosIconKey,
): KozmosIconDefinition | undefined {
  const resolvedName = resolveIconName(name);
  return kozmosIconDefinitions.find((icon) => icon.name === resolvedName);
}

export function isKozmosIconKey(name: string): name is KozmosIconKey {
  return getIconComponent(name as KozmosIconKey) !== undefined;
}
