import type { Meta, StoryObj } from "@storybook/react";
import { fn } from "@storybook/test";
import { Notice } from "./Notice";
import { Button } from "../Button";

const meta = {
  title: "Product SDK/Notice",
  component: Notice,
  parameters: { layout: "centered" },
  decorators: [
    (Story) => (
      <div className="w-[22rem]">
        <Story />
      </div>
    ),
  ],
} satisfies Meta<typeof Notice>;

export default meta;
type Story = StoryObj<typeof meta>;

/**
 * Story 14's dietary notice. One line above the results, with the full legal
 * wording a tap away — it was 114px of box before.
 */
export const Collapsed: Story = {
  args: {
    summary: "AI results may be incomplete. Check allergens with the venue.",
    children:
      "These results are AI-assisted and may be incomplete or out of date. If you have an allergy or intolerance, confirm with the venue or its staff before you order.",
  },
};

export const Expanded: Story = {
  args: { ...Collapsed.args, defaultExpanded: true },
};

/**
 * Help first, not a result list. Nothing is hidden and the way to act is
 * already on screen: nobody in an emergency should have to find a "More" link.
 */
export const Emergency: Story = {
  args: {
    tone: "critical",
    collapsible: false,
    summary: "If someone's life is in danger, call 112 now",
    children:
      "Airport staff can help too. The nearest help points are below.",
    action: (
      <Button onClick={fn()} variant="destructive">
        Call 112
      </Button>
    ),
  },
};

/** No detail, so no disclosure is offered. */
export const SingleLine: Story = {
  args: {
    tone: "info",
    summary: "Results are generated by AI and may contain mistakes.",
  },
};
