// Generated by scripts/build-icon-code-connect.mjs. Do not edit by hand.
//
// One connection per Icon / * component on the library's Icons page, from the
// node id recorded in figma-icons-2026-09-22-0947Z.json. Every icon reaches
// code through Icon's name prop, so the mapping survives a change of which
// component the registry resolves that name to.
import figma from "@figma/code-connect";
import { Icon } from "./Icon";









figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1862",
  {
    example: () => <Icon name="trash-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1867",
  {
    example: () => <Icon name="upload-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1872",
  {
    example: () => <Icon name="user-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1877",
  {
    example: () => <Icon name="users-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1882",
  {
    example: () => <Icon name="wifi" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1887",
  {
    example: () => <Icon name="x-close" />,
  },
);
