// Generated by scripts/build-icon-code-connect.mjs. Do not edit by hand.
//
// One connection per Icon / * component on the library's Icons page, from the
// node id recorded in figma-icons-2026-09-22-0947Z.json. Every icon reaches
// code through Icon's name prop, so the mapping survives a change of which
// component the registry resolves that name to.
import figma from "@figma/code-connect";
import { Icon } from "./Icon";

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1702",
  {
    example: () => <Icon name="activity" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1707",
  {
    example: () => <Icon name="alert-circle" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1712",
  {
    example: () => <Icon name="alert-triangle" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-8850",
  {
    example: () => <Icon name="arrow-down" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1717",
  {
    example: () => <Icon name="arrow-left" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1722",
  {
    example: () => <Icon name="arrow-right" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-8859",
  {
    example: () => <Icon name="arrow-up" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1727",
  {
    example: () => <Icon name="bell-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-11411",
  {
    example: () => <Icon name="bookmark" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1732",
  {
    example: () => <Icon name="building-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1737",
  {
    example: () => <Icon name="bus" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1742",
  {
    example: () => <Icon name="calendar" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-11744",
  {
    example: () => <Icon name="calendar-check-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1747",
  {
    example: () => <Icon name="check" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1752",
  {
    example: () => <Icon name="chevron-down" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1757",
  {
    example: () => <Icon name="chevron-left" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1762",
  {
    example: () => <Icon name="chevron-right" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1767",
  {
    example: () => <Icon name="chevron-up" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1772",
  {
    example: () => <Icon name="clock" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-11869",
  {
    example: () => <Icon name="clock-plus" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1777",
  {
    example: () => <Icon name="compass-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1782",
  {
    example: () => <Icon name="download-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1787",
  {
    example: () => <Icon name="edit-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-12232",
  {
    example: () => <Icon name="eye" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-12555",
  {
    example: () => <Icon name="feather" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-9784",
  {
    example: () => <Icon name="flip-backward" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-12890",
  {
    example: () => <Icon name="globe-02" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-13389",
  {
    example: () => <Icon name="heart" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1792",
  {
    example: () => <Icon name="home-line" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1797",
  {
    example: () => <Icon name="info-circle" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-13862",
  {
    example: () => <Icon name="layout-alt-02" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-13949",
  {
    example: () => <Icon name="loading-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1802",
  {
    example: () => <Icon name="lock-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-13954",
  {
    example: () => <Icon name="mail-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1807",
  {
    example: () => <Icon name="map-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1812",
  {
    example: () => <Icon name="marker-pin-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1817",
  {
    example: () => <Icon name="menu-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1822",
  {
    example: () => <Icon name="minus" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1827",
  {
    example: () => <Icon name="navigation-pointer-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-13959",
  {
    example: () => <Icon name="phone" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1832",
  {
    example: () => <Icon name="plus" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1837",
  {
    example: () => <Icon name="qr-code-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1842",
  {
    example: () => <Icon name="route" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1847",
  {
    example: () => <Icon name="scan" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1852",
  {
    example: () => <Icon name="search-md" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1857",
  {
    example: () => <Icon name="settings-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-13964",
  {
    example: () => <Icon name="share-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-13969",
  {
    example: () => <Icon name="shopping-bag-02" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-10629",
  {
    example: () => <Icon name="stars-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-10974",
  {
    example: () => <Icon name="switch-vertical-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1968-13974",
  {
    example: () => <Icon name="taxonomy-amenity-space-desk" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1968-13980",
  {
    example: () => <Icon name="taxonomy-entrance-exit" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1968-13983",
  {
    example: () => <Icon name="taxonomy-food-beverage-space" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1968-13986",
  {
    example: () => <Icon name="taxonomy-parking-space" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1968-13989",
  {
    example: () => <Icon name="taxonomy-retail-space" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1968-13996",
  {
    example: () => <Icon name="taxonomy-security-space" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1968-13999",
  {
    example: () => <Icon name="taxonomy-service-space-office" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1968-14002",
  {
    example: () => <Icon name="taxonomy-transportation-space-boarding-gate" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1862",
  {
    example: () => <Icon name="trash-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1867",
  {
    example: () => <Icon name="upload-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1872",
  {
    example: () => <Icon name="user-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1877",
  {
    example: () => <Icon name="users-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1882",
  {
    example: () => <Icon name="wifi" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1887",
  {
    example: () => <Icon name="x-close" />,
  },
);
