/**
 * The map shell's geometry engines, under test — MAP-566.
 *
 * Three of them: the polygon SPLIT, the SNAP index, and the SQUARE (Straighten) pass. All three
 * live inside `public/map/index.html` between marker comments, and all three are extracted from it
 * rather than copied here, so what is tested is what ships.
 *
 * `public/map/index.html` is a script tag, not a module, so there is nothing to import. Rather than
 * copy the algorithm here — where it would rot the moment somebody fixed a bug in the real one —
 * this extracts the code BETWEEN THE MARKERS out of that file, writes it out as a module, and
 * imports it. The code under test is therefore literally the code that ships; delete the markers
 * and this fails loudly rather than quietly testing a stale copy.
 *
 *     node scratch/geometry.test.mjs
 *
 * Plain screen-space arithmetic throughout, so no map, no DOM, no browser.
 */
import { readFileSync, writeFileSync, unlinkSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const src = readFileSync(join(here, "..", "public", "map", "index.html"), "utf8");

/** Every marker-delimited engine in the map shell, in the order they must be defined. */
const BLOCKS = ["SPLIT-ENGINE", "SNAP-ENGINE", "GUIDE-ENGINE", "COMBINE-ENGINE", "SQUARE-ENGINE",
                "FOCUS-ENGINE",
                "BOX-ENGINE"];
const engine = BLOCKS.map((name) => {
  const from = src.indexOf(`/* ${name}-START`);
  const to = src.indexOf(`/* ${name}-END */`);
  if (from < 0 || to < 0) {
    console.error(`could not find the ${name} markers in public/map/index.html`);
    process.exit(1);
  }
  return src.slice(src.indexOf("*/", from) + 2, to);
}).join("\n");

const generated = join(here, "geometry.generated.mjs");
writeFileSync(
  generated,
  `// GENERATED by geometry.test.mjs from public/map/index.html — do not edit, do not commit.\n` +
    `${engine}\nexport { splitRingsByLine, ringSignedArea, ringOpen,\n` +
      `  segClosest, buildSnapIndex, snapQuery, dominantAngle, squareRings,\n` +
      `  angleGuide, alignGuides, resolveGuides, bestAngleGuide, rayIntersect,\n` +
      `  guideTolFor, GUIDE_TOLS, GUIDE_WIDE_TOLS, GUIDE_STEP_FREE, GUIDE_STEP_SNAP,\n` +
      `  segPairClosest, findBridge, bridgeRings, combineRings,\n` +
      `  ringGap, ringSetArea, largestSet, wallBetween,\n` +
      `  focusView, focusPan, FOCUS_MARGIN,\n` +
      `  unwrapGrid, orientedBox, geomResizeCursor };\n`,
);

let mod;
try {
  mod = await import(pathToFileURL(generated).href);
} finally {
  unlinkSync(generated);
}
const {
  splitRingsByLine, ringSignedArea, ringOpen,
  segClosest, buildSnapIndex, snapQuery, dominantAngle, squareRings,
  angleGuide, alignGuides, resolveGuides, bestAngleGuide, rayIntersect,
  guideTolFor, GUIDE_TOLS, GUIDE_WIDE_TOLS, GUIDE_STEP_FREE, GUIDE_STEP_SNAP,
  segPairClosest, findBridge, bridgeRings, combineRings,
  ringGap, ringSetArea, largestSet, wallBetween,
  focusView, focusPan, FOCUS_MARGIN,
  unwrapGrid, orientedBox, geomResizeCursor,
} = mod;

/* ── helpers ──────────────────────────────────────────────────────────────── */

let failures = 0;
let checks = 0;

function check(name, cond, detail) {
  checks++;
  if (cond) return;
  failures++;
  console.error(`  ✗ ${name}${detail ? ` — ${detail}` : ""}`);
}

const area = (ring) => Math.abs(ringSignedArea(ringOpen(ring)));
const areaOf = (rings) => rings.reduce((n, r) => n + area(r), 0);

/** Is this a ring anyone can trust? Closed, at least a triangle, no repeated neighbours. */
function wellFormed(ring) {
  if (ring.length < 4) return "fewer than 3 distinct points";
  const first = ring[0], last = ring[ring.length - 1];
  if (first[0] !== last[0] || first[1] !== last[1]) return "not closed";
  for (const [x, y] of ring) if (!Number.isFinite(x) || !Number.isFinite(y)) return "non-finite point";
  const open = ringOpen(ring);
  for (let i = 0; i < open.length; i++) {
    const p = open[i], q = open[(i + 1) % open.length];
    if (Math.hypot(p[0] - q[0], p[1] - q[1]) < 1e-9) return `repeated point at ${i}`;
  }
  if (Math.abs(ringSignedArea(open)) < 1e-9) return "zero area";
  return null;
}

/**
 * The invariants every successful cut must satisfy, whatever the shape:
 * both halves exist, every ring is well formed, and the pieces add back up to the original.
 */
function expectSplit(name, rings, a, b, { leftRings, rightRings }) {
  const res = splitRingsByLine(rings, a, b);
  if (!res.ok) {
    check(name, false, `expected a split, was refused with "${res.reason}"`);
    return null;
  }
  check(`${name} · left ring count`, res.left.length === leftRings,
        `expected ${leftRings}, got ${res.left.length}`);
  check(`${name} · right ring count`, res.right.length === rightRings,
        `expected ${rightRings}, got ${res.right.length}`);
  for (const [side, list] of [["left", res.left], ["right", res.right]]) {
    list.forEach((r, i) => {
      const bad = wellFormed(r);
      check(`${name} · ${side}[${i}] well formed`, !bad, bad || "");
    });
  }
  // Area is the honest check: a cut neither creates nor destroys floor.
  const before = areaOf(rings);
  const after = areaOf(res.left) + areaOf(res.right);
  check(`${name} · area conserved`, Math.abs(before - after) < before * 1e-9,
        `before ${before.toFixed(6)}, after ${after.toFixed(6)}`);
  // Provenance: the caller needs to know which input ring each piece came from to keep track of
  // what is new, and it cannot recover that from two flattened lists.
  check(`${name} · every piece says where it came from`,
        res.leftFrom.length === res.left.length &&
          res.rightFrom.length === res.right.length &&
          [...res.leftFrom, ...res.rightFrom].every((j) => j >= 0 && j < rings.length),
        `leftFrom ${JSON.stringify(res.leftFrom)}, rightFrom ${JSON.stringify(res.rightFrom)}`);
  check(`${name} · every input ring is accounted for`,
        rings.every((_, j) => typeof res.wasCut[j] === "boolean" &&
                              [...res.leftFrom, ...res.rightFrom].includes(j)),
        `wasCut ${JSON.stringify(res.wasCut)}`);
  return res;
}

function expectNoSplit(name, rings, a, b, reason) {
  const res = splitRingsByLine(rings, a, b);
  check(name, !res.ok && res.reason === reason,
        res.ok ? `split into ${res.left.length}/${res.right.length}` : `refused with "${res.reason}"`);
}

const close = (pts) => [...pts.map((p) => p.slice()), pts[0].slice()];

/* ── the shapes ───────────────────────────────────────────────────────────── */

// A plain 10×10 room.
const SQUARE = close([[0, 0], [10, 0], [10, 10], [0, 10]]);

// A U, opening upward: arms at x∈[0,3] and x∈[7,10], joined by a base at y∈[0,3].
// The shape MAP-566 called out by name — a horizontal cut across both arms must give three pieces.
const U = close([
  [0, 0], [10, 0], [10, 10], [7, 10], [7, 3], [3, 3], [3, 10], [0, 10],
]);

// An L.
const L = close([[0, 0], [10, 0], [10, 4], [4, 4], [4, 10], [0, 10]]);

// A comb with three teeth — six crossings' worth of concavity, to push the chord pairing.
const COMB = close([
  [0, 0], [12, 0], [12, 10], [10, 10], [10, 4], [8, 4], [8, 10],
  [6, 10], [6, 4], [4, 4], [4, 10], [2, 10], [2, 4], [0, 4],
]);

console.log("split engine");

/* 1. The easy one, and the one a convex-only implementation also gets right. */
expectSplit("square, cut across the middle", [SQUARE], [-5, 5], [15, 5],
            { leftRings: 1, rightRings: 1 });

/* 2. Diagonal — the cut hits two edges at an angle, not at right angles. */
expectSplit("square, diagonal cut", [SQUARE], [-5, -4], [15, 6],
            { leftRings: 1, rightRings: 1 });

/* 3. The recorded bar: a concave U cut across BOTH arms. Four crossings, two chords. Above the cut
      the arms are two separate pieces; below it the base is one. A convex-only implementation
      joins the arm tips through thin air and mangles the floor — this is the case that catches it. */
{
  const res = expectSplit("U, cut across both arms", [U], [-5, 6], [15, 6],
                          { leftRings: 2, rightRings: 1 });
  if (res) {
    // The two upper pieces must be the arm TIPS: 3 wide, 4 tall.
    const tips = res.left.map(area).sort((x, y) => x - y);
    check("U · arm tips are 3×4", tips.every((t) => Math.abs(t - 12) < 1e-9),
          `got ${tips.map((t) => t.toFixed(3)).join(", ")}`);
    // …and nothing spans the gap between them.
    for (const r of res.left) {
      const xs = ringOpen(r).map((p) => p[0]);
      const span = Math.max(...xs) - Math.min(...xs);
      check("U · no piece spans the gap", span <= 3 + 1e-9, `span ${span.toFixed(3)}`);
    }
  }
}

/* 4. The same U, cut low enough to miss the arms — one crossing pair, two ordinary pieces. */
expectSplit("U, cut below the arms", [U], [-5, 1.5], [15, 1.5],
            { leftRings: 1, rightRings: 1 });

/* 5. A vertical cut down the U's left arm. */
expectSplit("U, cut down one arm", [U], [1.5, -5], [1.5, 15],
            { leftRings: 1, rightRings: 1 });

/* 6. L, cut either way through the reflex corner region. */
expectSplit("L, horizontal cut", [L], [-5, 2], [15, 2], { leftRings: 1, rightRings: 1 });
expectSplit("L, vertical cut", [L], [2, -5], [2, 15], { leftRings: 1, rightRings: 1 });

/* 7. Three teeth: a cut across all of them yields three tips on one side, the spine on the other.
      Six crossings, three chords — the pairing has to get every one of them right. */
{
  const res = expectSplit("comb, cut across all three teeth", [COMB], [-5, 7], [20, 7],
                          { leftRings: 3, rightRings: 1 });
  if (res) {
    const tips = res.left.map(area);
    check("comb · every tooth is 2×3", tips.every((t) => Math.abs(t - 6) < 1e-9),
          `got ${tips.map((t) => t.toFixed(3)).join(", ")}`);
  }
}

/* 8. Straight through two opposite VERTICES. Both are already on the line, so nothing is inserted
      and the whole thing rests on the run/crossing classification. */
expectSplit("square, corner to corner through the vertices", [SQUARE], [-5, -5], [15, 15],
            { leftRings: 1, rightRings: 1 });

/* 9. A cut that only TOUCHES a corner — `y = x + 10` rests on (0,10) with the square below it.
      The classic trap: one on-line vertex, no crossing, and an implementation that counts touches
      produces a zero-area second piece and calls it a room. */
expectNoSplit("square, line grazing a corner", [SQUARE], [-5, 5], [5, 15], "miss");

/* 10. A cut running ALONG an edge — a whole collinear run on the line, still not a cut. */
expectNoSplit("square, line along the bottom edge", [SQUARE], [-5, 0], [15, 0], "miss");

/* 11. Misses entirely. */
expectNoSplit("square, line well clear", [SQUARE], [-5, 20], [15, 20], "miss");

/* 12. A degenerate cut — the two clicks landed on the same pixel. */
expectNoSplit("square, zero-length cut", [SQUARE], [5, 5], [5, 5], "miss");

/* 12b. ⚠️ The degenerate this suite was written to find. A cut laid exactly along the U's inner
        edge crosses at x=0 and x=10, but the stretch between x=3 and x=7 is OUTSIDE the shape —
        so pairing those two crossings joins the arms straight through the notch. Area still
        balances, which is exactly why area alone is not enough of a check. It must be refused. */
expectNoSplit("U, cut exactly along the inner edge", [U], [-5, 3], [15, 3], "tangent");

/* 12c. …and the same refusal for a cut that crosses cleanly AND grazes the reflex corner on the
        way. `y = 8 − x` passes through the L's inner corner (4,4) with both its neighbours above
        the line, and crosses the outline properly at (8,0) and (0,8). Two crossings and one touch:
        pair the crossings and you get a plausible-looking piece bounded by a line that never
        entered the shape. */
expectNoSplit("L, cut crossing but grazing the reflex corner", [L], [-2, 10], [12, -4], "tangent");

/* 12d. The collinear run that IS a crossing must still work — an edge lying along the cut while
        the ring passes from one side to the other. Nothing to refuse here; the run's far end
        carries the crossing and the on-line points add no area to whichever piece they land in. */
{
  const STEP = close([[0, 0], [10, 0], [10, 5], [6, 5], [6, 10], [0, 10]]);
  const res = expectSplit("step, cut along the horizontal edge", [STEP], [-5, 5], [15, 5],
                          { leftRings: 1, rightRings: 1 });
  if (res) {
    check("step · pieces are 50 and 30",
          Math.abs(areaOf(res.right) - 50) < 1e-9 && Math.abs(areaOf(res.left) - 30) < 1e-9,
          `got ${areaOf(res.right).toFixed(3)} and ${areaOf(res.left).toFixed(3)}`);
  }
}

/* 13. A cut down the U's notch separates the two arms, and must not invent geometry in the gap. */
expectSplit("U, cut down the notch", [U], [5, -5], [5, 15], { leftRings: 1, rightRings: 1 });

/* 14. A feature that is already two rings. The line crosses one and misses the other — the missed
       ring must travel whole to its own side rather than vanish. */
{
  const far = close([[20, 0], [30, 0], [30, 10], [20, 10]]);
  const res = expectSplit("two rings, cut through one", [SQUARE, far], [5, -5], [5, 15],
                          { leftRings: 1, rightRings: 2 });
  if (res) {
    check("two rings · the untouched ring survives whole",
          res.right.some((r) => Math.abs(area(r) - 100) < 1e-9),
          `right areas ${res.right.map((r) => area(r).toFixed(1)).join(", ")}`);
    // The caller mints new piece ids for cut rings only, so this distinction has to be right or an
    // untouched ring is announced as a brand-new piece of a feature nobody split.
    check("two rings · only the crossed ring is marked cut",
          res.wasCut[0] === true && res.wasCut[1] === false,
          `wasCut ${JSON.stringify(res.wasCut)}`);
  }
}

/* 15. Both rings cut by the same line. */
{
  const far = close([[20, 0], [30, 0], [30, 10], [20, 10]]);
  expectSplit("two rings, cut through both", [SQUARE, far], [-5, 5], [40, 5],
              { leftRings: 2, rightRings: 2 });
}

/* 16. Winding must not matter — the same square, wound the other way. */
expectSplit("square wound clockwise", [close([[0, 0], [0, 10], [10, 10], [10, 0]])],
            [-5, 5], [15, 5], { leftRings: 1, rightRings: 1 });

/* 17. Direction of the cut must not matter either: a→b and b→a swap the labels, nothing else. */
{
  const ab = splitRingsByLine([U], [-5, 6], [15, 6]);
  const ba = splitRingsByLine([U], [15, 6], [-5, 6]);
  check("cut direction only swaps the sides",
        ab.ok && ba.ok && ab.left.length === ba.right.length && ab.right.length === ba.left.length,
        ab.ok && ba.ok
          ? `${ab.left.length}/${ab.right.length} vs ${ba.left.length}/${ba.right.length}`
          : "refused");
}

/* 18. Real-world scale. The tolerance is relative to the cut's length, so a long cut across a
       small shape must still behave — this is the one that catches an absolute epsilon. */
expectSplit("long cut across a small shape",
            [close([[100, 100], [104, 100], [104, 104], [100, 104]])],
            [-5000, 102], [5000, 102], { leftRings: 1, rightRings: 1 });


/* ══ snap engine ═══════════════════════════════════════════════════════════════ */

console.log("\nsnap engine");

/* S1. The nearest point on a segment, including past both ends. */
{
  const near = (n, got, want) => check(n, Math.hypot(got[0]-want[0], got[1]-want[1]) < 1e-9,
    `got ${got}, want ${want}`);
  near("foot lands mid-segment", segClosest(5, 5, 0, 0, 10, 0), [5, 0]);
  near("clamps past the start", segClosest(-5, 3, 0, 0, 10, 0), [0, 0]);
  near("clamps past the end", segClosest(99, 3, 0, 0, 10, 0), [10, 0]);
  near("a zero-length segment is its own point", segClosest(4, 4, 7, 7, 7, 7), [7, 7]);
  near("works on a diagonal", segClosest(0, 10, 0, 0, 10, 10), [5, 5]);
}

/* S2. A corner wins a near-tie — meeting a corner has to stay easy. */
{
  const idx = buildSnapIndex([[100, 100]], [[80, 96, 200, 96]], 24);
  const hit = snapQuery(idx, 100, 99, 10);   // corner 1px away, edge 3px away
  check("a corner wins a near-tie", hit && hit.kind === "corner",
        hit ? hit.kind + " @" + hit.d.toFixed(2) : "null");
}

/* S2b. ⚠️ THE REGRESSION. A corner in range used to win outright, so in floor-plan geometry — where
        some corner is nearly always within the radius — the edge was found and then always lost.
        Edge snapping was unreachable in exactly the geometry it was built for. Here the corner is
        9px off and the edge 1px: the edge is plainly what you were aiming at. */
{
  const idx = buildSnapIndex([[100, 91]], [[0, 100, 400, 100]], 24);
  const hit = snapQuery(idx, 100, 99, 10);
  check("a clearly closer edge beats a distant corner", hit && hit.kind === "edge",
        hit ? `${hit.kind} @${hit.d.toFixed(2)}` : "null");
}

/* S2c. The bias is the whole rule: just inside it the corner holds, just outside it the edge takes
        over. Pinned so the constant cannot drift without a test noticing. */
{
  const edge = [[0, 100, 400, 100]];
  const held = snapQuery(buildSnapIndex([[100, 96]], edge, 24), 100, 100, 10); // corner 4, edge 0
  check("corner holds inside the bias", held && held.kind === "corner",
        held ? held.kind : "null");
  const lost = snapQuery(buildSnapIndex([[100, 94]], edge, 24), 100, 100, 10); // corner 6, edge 0
  check("…and yields outside it", lost && lost.kind === "edge", lost ? lost.kind : "null");
}

/* S3. An edge is found when no corner is in range — the case that did not exist before. */
{
  const idx = buildSnapIndex([[500, 500]], [[0, 200, 400, 200]], 24);
  const hit = snapQuery(idx, 210, 206, 10);
  check("snaps onto an edge", hit && hit.kind === "edge", hit ? hit.kind : "null");
  check("edge snap is the perpendicular foot",
        hit && Math.abs(hit.x - 210) < 1e-9 && Math.abs(hit.y - 200) < 1e-9,
        hit ? `${hit.x}, ${hit.y}` : "null");
}

/* S4. Nothing within the radius means no snap — a tool that always snaps is unusable. */
{
  const idx = buildSnapIndex([[0, 0]], [[0, 200, 400, 200]], 24);
  check("out of range returns null", snapQuery(idx, 210, 260, 10) === null);
  check("a null index never throws", snapQuery(null, 1, 2, 10) === null);
}

/* S5. The grid must not change the answer — the index is an optimisation, not a behaviour.
       Brute force over random data, against the same query. */
{
  let mismatches = 0;
  let seed = 12345;
  const rnd = () => (seed = (seed * 1103515245 + 12345) % 2147483648) / 2147483648;
  const verts = Array.from({ length: 400 }, () => [rnd() * 2000, rnd() * 2000]);
  const segs = Array.from({ length: 400 }, () => {
    const x = rnd() * 2000, y = rnd() * 2000;
    return [x, y, x + (rnd() - 0.5) * 300, y + (rnd() - 0.5) * 300];
  });
  const idx = buildSnapIndex(verts, segs, 24);
  for (let i = 0; i < 500; i++) {
    const px = rnd() * 2000, py = rnd() * 2000, R = 10;
    // the honest O(n) answer, with the same biased corner-beats-edge rule
    let bv = null, bvd = R, be = null, bed = R;
    for (const v of verts) { const d = Math.hypot(v[0]-px, v[1]-py); if (d < bvd) { bvd = d; bv = v; } }
    for (const sg of segs) {
      const q = segClosest(px, py, sg[0], sg[1], sg[2], sg[3]);
      const d = Math.hypot(q[0]-px, q[1]-py); if (d < bed) { bed = d; be = q; }
    }
    const BIAS = 5;   // must match SNAP_CORNER_BIAS in the shell
    const want = bv && (!be || bvd <= bed + BIAS) ? { kind: "corner", d: bvd }
               : be ? { kind: "edge", d: bed } : null;
    const got = snapQuery(idx, px, py, R);
    const same = (!want && !got) ||
      (want && got && want.kind === got.kind && Math.abs(want.d - got.d) < 1e-9);
    if (!same) mismatches++;
  }
  check("the index agrees with brute force on 500 random queries", mismatches === 0,
        `${mismatches} disagreed`);
}


/* ══ guide engine ══════════════════════════════════════════════════════════════ */

console.log("\nguide engine");

/* G1. A cursor near a 15° ray is pulled onto it; one that is not, is not. */
{
  const on = angleGuide(0, 0, 100, 2, 15, 2.5);          // ~1.1° off horizontal
  check("a near-horizontal drag catches 0°", on && Math.abs(on.deg % 180) < 1e-9,
        on ? `${on.deg}°` : "null");
  check("…and lands exactly on the ray", on && Math.abs(on.y) < 1e-9, on ? String(on.y) : "null");
  check("a deliberate 8° is left alone", angleGuide(0, 0, 100, 14, 15, 2.5) === null);
}

/* G2. The projection is perpendicular — the point slides onto the guide, it does not jump along it. */
{
  const g = angleGuide(0, 0, 100, 3, 15, 5);
  check("distance along the ray is the projection, not the raw length",
        g && Math.abs(g.x - 100) < 0.2, g ? `x=${g.x.toFixed(3)}` : "null");
}

/* G3. Every 15° step is reachable, including the diagonals and behind the anchor. */
{
  for (const want of [0, 45, 90, 135, 180, 270]) {
    const a = want * Math.PI / 180;
    const g = angleGuide(0, 0, Math.cos(a) * 80, Math.sin(a) * 80, 15, 2.5);
    check(`${want}° is a guide`, g && Math.abs(((g.deg - want) % 360 + 360) % 360) < 1e-6,
          g ? `${g.deg}°` : "null");
  }
}

/* G4. Tracking: x and y are independent, and catching BOTH is the point — the cursor lands on an
       intersection that neither corner occupies. */
{
  const refs = [[100, 500], [700, 300]];
  const g = resolveGuides(null, 103, 297, refs, false);
  check("x is taken from one corner", Math.abs(g.x - 100) < 1e-9, String(g.x));
  check("y is taken from another", Math.abs(g.y - 300) < 1e-9, String(g.y));
  check("and both are explained", g.guides.length === 2, String(g.guides.length));
}

/* G5. Nothing near means nothing happens — a guide that always fires is a guide you fight. */
{
  const g = resolveGuides(null, 400, 400, [[100, 500], [700, 300]], false);
  check("no alignment leaves the point alone",
        g.x === 400 && g.y === 400 && g.guides.length === 0, `${g.x},${g.y}`);
}

/* G6. ⚠️ The precedence rule. Alignment beats a tight angle guide, because agreeing with the room
       next door matters more than a round number of degrees — but the modifier means "on the
       angle" and overrides it outright. */
{
  const refs = [[103, 9999]];                      // an x-alignment 0px away at the cursor
  const free = resolveGuides([0, 0], 103, 1, refs, false);
  check("alignment wins when free", free.guides.some((g) => g.kind === "align"),
        JSON.stringify(free.guides.map((g) => g.kind)));
  const held = resolveGuides([0, 0], 103, 1, refs, true);
  check("the modifier forces the angle", held.guides.length === 1 && held.guides[0].kind === "angle",
        JSON.stringify(held.guides.map((g) => g.kind)));
  check("…and the modifier's wider capture reaches further",
        angleGuide(0, 0, 100, 12, 15, 2.5) === null && angleGuide(0, 0, 100, 12, 15, 7.5) !== null);
}

/* G7. With no anchor there is no angle to guide by, and that must not throw. */
{
  const g = resolveGuides(null, 50, 50, [], false);
  check("no anchor, no refs, no crash", g.x === 50 && g.y === 50 && g.guides.length === 0);
  check("an anchor on top of the cursor is not a direction",
        angleGuide(10, 10, 10, 10, 15, 2.5) === null);
}


/* G8. ⚠️ THE REGRESSION. Guides are measured from a REFERENCE WALL, not from the screen.
       A building at 23° is still a rectilinear building; offering it right angles to the monitor
       is offering it nothing. Here the reference wall runs at 23° and the cursor is dragged
       roughly square to it — that must catch, and screen-absolute guides cannot see it. */
{
  const base = 23;
  const want = base + 90;
  const a = want * Math.PI / 180;
  const px = Math.cos(a) * 100, py = Math.sin(a) * 100;
  check("square to a 23° wall is not a screen angle",
        angleGuide(0, 0, px, py, 15, 2.5, 0) === null);
  const g = angleGuide(0, 0, px, py, 15, 2.5, base);
  check("…but is caught when measured from that wall", g !== null);
  check("…and is reported as 90° TO THE WALL, not 113° to the screen",
        g && Math.abs(g.rel - 90) < 1e-9, g ? `rel ${g.rel}` : "null");
  check("…while the ray drawn is the absolute bearing",
        g && Math.abs(g.deg - 113) < 1e-9, g ? `deg ${g.deg}` : "null");
}

/* G9. Carrying straight on from a wall is 0° relative — the other thing you constantly want. */
{
  const base = -37;
  const a = base * Math.PI / 180;
  const g = angleGuide(0, 0, Math.cos(a) * 60, Math.sin(a) * 60, 15, 2.5, base);
  check("continuing a wall reads as 0°", g && Math.abs(g.rel) < 1e-9, g ? `rel ${g.rel}` : "null");
}

/* G10. Several walls to refer to: the nearest reference wins, so the guide that appears is the one
        the geometry justifies rather than whichever was listed first. */
{
  const bases = [10, 80];               // two walls, 70° apart
  const a = 79 * Math.PI / 180;         // 1° off the second wall's own direction
  const px = Math.cos(a) * 100, py = Math.sin(a) * 100;
  const g = bestAngleGuide(0, 0, px, py, 15, 2.5, bases);
  check("the nearer reference wall wins", g && Math.abs(g.base - 80) < 1e-9,
        g ? `base ${g.base}` : "null");
  check("…and it reads as 0° to that wall", g && Math.abs(g.rel) < 1e-9,
        g ? `rel ${g.rel}` : "null");
}

/* G11. With nothing to refer to — the first edge of a shape drawn from nothing — screen axes are
        the honest fallback rather than an error. */
{
  const g = bestAngleGuide(0, 0, 100, 1, 15, 2.5, []);
  check("no reference falls back to the screen", g && Math.abs(g.deg) < 1e-9,
        g ? `deg ${g.deg}` : "null");
  check("an undefined base list does not throw",
        bestAngleGuide(0, 0, 100, 1, 15, 2.5, undefined) !== null);
}


/** Screen bearing a→b in degrees — the test's own copy, for building fixtures. */
const bearingOf = (a, b) => Math.atan2(b[1] - a[1], b[0] - a[0]) * 180 / Math.PI;

/* G12. Ray crossing, and its refusal to guess. */
{
  const X = rayIntersect([0, 0], [1, 0], [10, -10], [0, 1]);
  check("two rays cross where they should",
        X && Math.abs(X[0] - 10) < 1e-9 && Math.abs(X[1]) < 1e-9, X ? String(X) : "null");
  check("parallel rays have no crossing", rayIntersect([0, 0], [1, 0], [0, 5], [1, 0]) === null);
  check("near-parallel rays are refused, not chased to infinity",
        rayIntersect([0, 0], [1, 0], [0, 5], [1, 0.01]) === null);
}

/* G13. ⚠️ THE ONE OLCAY ASKED FOR: square at the corner BEFORE and the corner AFTER at once.
        Outline runs (0,0) → P(100,0) → V → N(200,100) → (200,200). A ray from P square to the wall
        arriving at it is vertical through x=100; a ray from N square to the wall leaving it is
        horizontal through y=100. The corner that squares BOTH ends is exactly (100,100) — a point
        neither guide could have produced alone. */
{
  const ring = [[0, 0], [100, 0], [140, 60], [200, 100], [200, 200]];
  const anchors = [
    { at: [100, 0], bases: [bearingOf([0, 0], [100, 0])] },      // wall arriving at P
    { at: [200, 100], bases: [bearingOf([200, 100], [200, 200])] }, // wall leaving N
  ];
  const g = resolveGuides(anchors, 104, 96, [], true);   // cursor near the crossing, Shift held
  check("both rays catch and the corner goes to their crossing", g.crossed === true,
        JSON.stringify(g.guides.map((x) => x.kind)));
  check("…which is exactly the double-square position",
        Math.abs(g.x - 100) < 1e-6 && Math.abs(g.y - 100) < 1e-6,
        `${g.x.toFixed(3)}, ${g.y.toFixed(3)}`);
  check("…and both guides are drawn, not just the winner", g.guides.length === 2,
        String(g.guides.length));
  void ring;
}

/* G14. Two guards, and they catch different things.
        Parallel rays never meet at all; rays a few degrees apart DO meet, but a thousand pixels
        away — which is a teleport, not a snap. */
{
  const parallel = resolveGuides(
    [{ at: [0, 0], bases: [0] }, { at: [0, 20], bases: [0] }], 300, 10, [], true);
  check("parallel guides do not pretend to cross", !parallel.crossed);
  check("…but one of them still guides", parallel.guides.length === 1,
        String(parallel.guides.length));

  // 3° apart: past the parallel guard, so only the distance check can refuse it. The rays meet
  // around x = -572, well over a thousand pixels from a cursor at (500, 15).
  const far = resolveGuides(
    [{ at: [0, 0], bases: [0] }, { at: [0, 30], bases: [3] }], 500, 15, [], true);
  check("a crossing a thousand pixels away is refused", !far.crossed);
}

/* G15. One anchor still behaves as it did — the cut passes a bare point and its bases. */
{
  const g = resolveGuides([0, 0], 100, 2, [], false, [0]);
  check("a bare anchor still guides", g.guides.length === 1 && g.guides[0].kind === "angle",
        JSON.stringify(g.guides));
  check("…and lands on the ray", Math.abs(g.y) < 1e-9, String(g.y));
}


/* G16. ⚠️ FREE MODE MUST BE FINE. Olcay: "still ignores less then 15 and tags them as 90 or 0."
        A corner at 86° is not a right angle, and a tool that rounds it to one and then prints
        "90°" has stopped reporting and started deciding. Every 5° is its own answer, and anything
        between them is left alone. */
{
  const at = (d, step, tols) => {
    const a = d * Math.PI / 180;
    return bestAngleGuide(0, 0, Math.cos(a) * 100, Math.sin(a) * 100, step, tols, [0]);
  };
  const free = (d) => at(d, GUIDE_STEP_FREE, GUIDE_TOLS);

  check("85° is its own guide, not a rounding of 90°",
        free(85) && Math.abs(free(85).rel - 85) < 1e-9,
        free(85) ? `${free(85).rel}°` : "MISSED");
  check("95° likewise", free(95) && Math.abs(free(95).rel - 95) < 1e-9,
        free(95) ? `${free(95).rel}°` : "MISSED");
  check("86° is nobody's guide and is left free", free(86) === null,
        free(86) ? `dragged to ${free(86).rel}°` : "free");
  check("87° too", free(87) === null, free(87) ? `dragged to ${free(87).rel}°` : "free");
  check("88° is left alone rather than called square", free(88) === null,
        free(88) ? `dragged to ${free(88).rel}°` : "free");
  check("90° still catches when you are all but on it",
        free(89.5) && Math.abs(free(89.5).rel - 90) < 1e-9,
        free(89.5) ? `${free(89.5).rel}°` : "MISSED");
  /**
   * ⚠️ The guarantee that matters is not how much of the circle is magnetised — it is **how far
   * anything is moved**. "Tagged as 90 or 0" was a complaint about corners being dragged up to 6°
   * onto a round number. Free mode may now nudge by at most `cardinal`, and by less than a degree
   * for an ordinary angle, so the readout never disagrees with the shape by more than a whisker.
   */
  let worst = 0, worstAt = null;
  for (let d = 0; d < 360; d += 0.1) {
    const g = free(d);
    if (!g) continue;
    let off = Math.abs(((g.rel - d) % 360 + 540) % 360 - 180);
    if (off > worst) { worst = off; worstAt = d; }
  }
  check("nothing is pulled further than the cardinal tolerance",
        worst <= GUIDE_TOLS.cardinal + 1e-6, `${worst.toFixed(2)}° at ${worstAt}°`);
  check("…and an ordinary angle by under a degree",
        GUIDE_TOLS.other < 1, `${GUIDE_TOLS.other}°`);
}

/* G17. ⚠️ AND SHIFT MUST BE COARSE — that is what Olcay asked for the round before: "when pressing
        shift … 90 degree". 85° and 95° land on square, because that is what the modifier is for. */
{
  const held = (d) => {
    const a = d * Math.PI / 180;
    return bestAngleGuide(0, 0, Math.cos(a) * 100, Math.sin(a) * 100,
                          GUIDE_STEP_SNAP, GUIDE_WIDE_TOLS, [0]);
  };
  for (const d of [85, 87, 90, 93, 95])
    check(`${d}° lands on square under the modifier`, held(d) && Math.abs(held(d).rel - 90) < 1e-9,
          held(d) ? `${held(d).rel}°` : "MISSED");
  check("…and the modifier still respects the 15° grid", held(75) && Math.abs(held(75).rel - 75) < 1e-9);
}

/* G18. No magnet may exceed half a step, or it steals from its neighbour and two guides claim the
        same cursor. */
{
  for (const k of ["cardinal", "half", "other"])
    check(`the free ${k} tolerance stays inside half a FREE step`,
          GUIDE_TOLS[k] <= GUIDE_STEP_FREE / 2 + 1e-9, `${GUIDE_TOLS[k]}° vs ${GUIDE_STEP_FREE / 2}°`);
  for (const k of ["cardinal", "half", "other"])
    check(`the modifier's ${k} tolerance stays inside half a SNAP step`,
          GUIDE_WIDE_TOLS[k] <= GUIDE_STEP_SNAP / 2 + 1e-9, `${GUIDE_WIDE_TOLS[k]}°`);
  check("the modifier's grid is coarser than the free one", GUIDE_STEP_SNAP > GUIDE_STEP_FREE,
        `${GUIDE_STEP_SNAP} vs ${GUIDE_STEP_FREE}`);
  check("grading picks cardinal for 90", guideTolFor(90, GUIDE_TOLS) === GUIDE_TOLS.cardinal);
  check("grading picks cardinal for 0", guideTolFor(0, GUIDE_TOLS) === GUIDE_TOLS.cardinal);
  check("grading picks half for 45", guideTolFor(45, GUIDE_TOLS) === GUIDE_TOLS.half);
  check("grading picks other for 75", guideTolFor(75, GUIDE_TOLS) === GUIDE_TOLS.other);
  check("grading wraps past a full turn", guideTolFor(450, GUIDE_TOLS) === GUIDE_TOLS.cardinal);
  check("grading handles negatives", guideTolFor(-90, GUIDE_TOLS) === GUIDE_TOLS.cardinal);
}


/* ══ combine engine ════════════════════════════════════════════════════════════ */

console.log("\ncombine engine");

/** Two 100×60 rooms with a wall-sized gap between them, left and right. */
const roomL = close([[0, 0], [100, 0], [100, 60], [0, 60]]);
const roomR = (gap) => close([[100 + gap, 0], [200 + gap, 0], [200 + gap, 60], [100 + gap, 60]]);

/* C1. Closest approach between two segments, including the parallel case the closed form fumbles. */
{
  const c = segPairClosest([0, 0], [100, 0], [0, 10], [100, 10]);
  check("parallel segments are 10 apart", c && Math.abs(c.d - 10) < 0.2, c ? c.d.toFixed(3) : "null");
  const d = segPairClosest([0, 0], [10, 0], [50, 0], [60, 0]);
  check("collinear but apart measures the end gap", d && Math.abs(d.d - 40) < 0.5,
        d ? d.d.toFixed(3) : "null");
}

/* C2. A wall-sized gap is bridged; a corridor-sized one is not. That threshold is the whole
       safeguard against combining two rooms that merely happen to be on the same floor. */
{
  check("a 6px wall is found", findBridge(roomL, roomR(6), 12) !== null);
  check("a 40px corridor is not", findBridge(roomL, roomR(40), 12) === null);
}

/**
 * Is `p` inside this ring? Ray casting — only ever used to assert what a join *contains*, which is
 * the one thing an area figure cannot tell you on its own: the right total can still be the wrong
 * shape.
 */
function inRing(ring, p) {
  const r = ringOpen(ring);
  let inside = false;
  for (let i = 0, j = r.length - 1; i < r.length; j = i++) {
    const [xi, yi] = r[i], [xj, yj] = r[j];
    if ((yi > p[1]) !== (yj > p[1]) &&
        p[0] < ((xj - xi) * (p[1] - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}

/* C3. The join is ONE ring, and it holds both rooms plus the wall between them — **exactly**. */
{
  const out = bridgeRings(roomL, roomR(6), 12);
  check("two rooms become one ring", out !== null);
  const bad = out && wellFormed(out);
  check("…and it is well formed", out && !bad, bad || "null");
  const a = out ? Math.abs(ringSignedArea(ringOpen(out))) : 0;
  /**
   * ⚠️ 6000 + 6000 for the rooms and 360 for the 6×60 wall, to the last decimal rather than within
   * a few hundred. The tolerance used to be ±400 and it was hiding the bug: the old stitch bridged
   * through the two NEAREST points, so it swallowed a wedge of the gap instead of the whole of it
   * and came out at 12180 — inside the tolerance, and visibly a seam on the map.
   */
  check("…with the whole wall's area inside it", Math.abs(a - 12360) < 1e-6, a.toFixed(4));
}

/* C3b. ⚠️ **The gap is genuinely FILLED**, which is the thing area alone cannot prove — the same
        total can be the wrong shape. Olcay, 2026-08-16: *"Combine should make 1 geometry by
        filling in between neatly."* Every one of these points was OUTSIDE the old join. */
{
  const out = bridgeRings(roomL, roomR(6), 12);
  for (const y of [1, 15, 30, 45, 59]) {
    check(`the middle of the wall at y=${y} is inside the joined room`,
          out && inRing(out, [103, y]));
  }
  check("…and so is each room's own middle",
        out && inRing(out, [50, 30]) && inRing(out, [156, 30]));
  check("…while the floor beyond the pair is still outside",
        out && !inRing(out, [-10, 30]) && !inRing(out, [220, 30]));
}

/* C4. ⚠️ Winding must be normalised. Two rings traversed opposite ways stitch into a
       figure-of-eight whose area partly cancels — the classic silent failure here. */
{
  const flipped = close([[100 + 6, 0], [100 + 6, 60], [200 + 6, 60], [200 + 6, 0]]);
  const out = bridgeRings(roomL, flipped, 12);
  check("opposite winding still joins cleanly", out !== null);
  const a = out ? Math.abs(ringSignedArea(ringOpen(out))) : 0;
  check("…and the area does not cancel itself away", Math.abs(a - 12360) < 1e-6, a.toFixed(4));
}

/* C5. Nothing near enough is `null`, not "one of them" — a combine that silently drops a room is
       worse than one that refuses. */
{
  check("far apart refuses", bridgeRings(roomL, roomR(200), 12) === null);
}

/* C6. Three in a row combine into one, whatever order they arrive in. */
{
  const a = close([[0, 0], [100, 0], [100, 60], [0, 60]]);
  const b = close([[106, 0], [206, 0], [206, 60], [106, 60]]);
  const c = close([[212, 0], [312, 0], [312, 60], [212, 60]]);
  for (const order of [[a, b, c], [c, a, b], [b, c, a]]) {
    const r = combineRings(order, 12);
    check("three in a row make one", r.rings.length === 1 && r.joined === 2,
          `${r.rings.length} ring(s), ${r.joined} join(s)`);
  }
}

/* C7. A room across the building is left alone rather than dragged in — two results, not one
       impossible one. */
{
  const near = close([[106, 0], [206, 0], [206, 60], [106, 60]]);
  const far = close([[900, 0], [1000, 0], [1000, 60], [900, 60]]);
  const r = combineRings([roomL, near, far], 12);
  check("the unreachable room stays separate", r.rings.length === 2 && r.joined === 1,
        `${r.rings.length} ring(s)`);
  const areas = r.rings.map((x) => Math.abs(ringSignedArea(ringOpen(x)))).sort((p, q) => p - q);
  check("…and keeps its own area untouched", Math.abs(areas[0] - 6000) < 1, areas[0].toFixed(0));
}

/* C8. A single ring in is the same ring out — combine of one is not an error. */
{
  const r = combineRings([roomL], 12);
  check("one ring passes through", r.rings.length === 1 && r.joined === 0);
}

/* C9. Rooms stacked vertically bridge just as well as side by side — no axis is special. */
{
  const top = close([[0, 0], [100, 0], [100, 60], [0, 60]]);
  const bot = close([[0, 66], [100, 66], [100, 126], [0, 126]]);
  const out = bridgeRings(top, bot, 12);
  check("a vertical wall bridges too", out !== null);
  const a = out ? Math.abs(ringSignedArea(ringOpen(out))) : 0;
  check("…with the same area logic", Math.abs(a - 12600) < 1e-6, a.toFixed(4));
}

/* ── the interaction's own rules ──────────────────────────────────────────────
   Everything above answers "what shape comes out". These four answer the questions the
   INTERACTION asks — which feature survives, and which walls are now inside — and they are
   engine code for the same reason the rest is: they are decisions, and a decision that is not
   tested is a decision somebody will quietly change. */

/* C10. The gap between two rings, both ways round. The second case is the one a vertex-to-vertex
        measure gets wrong: the nearest point is in the MIDDLE of an edge, not on a corner. */
{
  check("side-by-side rooms measure their wall",
        Math.abs(ringGap(roomL, roomR(6)) - 6) < 1e-6, String(ringGap(roomL, roomR(6))));
  // A ring whose only near point is mid-edge: a stub poking at the middle of roomL's right wall.
  const stub = close([[106, 28], [130, 28], [130, 32], [106, 32]]);
  check("a mid-edge approach is found", Math.abs(ringGap(roomL, stub) - 6) < 1e-6,
        String(ringGap(roomL, stub)));
  check("touching rings measure zero", ringGap(roomL, roomR(0)) < 1e-9);
}

/* C11. Area, and the identity rule built on it. ⚠️ If this ever silently returns 0 the rule
        degenerates to "whichever was clicked first", which is the exact thing it exists to avoid. */
{
  check("a 100×60 room is 6000", Math.abs(ringSetArea([roomL]) - 6000) < 1e-6);
  const big = close([[106, 0], [400, 0], [400, 60], [106, 60]]);
  check("the larger room keeps the identity", largestSet([[roomL], [big]]) === 1);
  check("…whichever order it arrives in", largestSet([[big], [roomL]]) === 0);
  // A tie goes to the first, which is the feature already open — the least surprising answer, and
  // the only one that does not depend on click order.
  check("a tie goes to the feature already open", largestSet([[roomL], [roomR(6)]]) === 0);
  /**
   * Two rings for one feature: a room and its annexe both count towards "largest". Sized so the
   * point is actually made — 6000 + 6000 beats 10000, while either ring ALONE would lose to it.
   */
  const mid = close([[500, 0], [600, 0], [600, 100], [500, 100]]);
  check("a multi-ring feature counts all of its rings",
        largestSet([[roomL, roomR(6)], [mid]]) === 0);
  check("…and one of those rings alone would not",
        largestSet([[roomL], [mid]]) === 1);
}

/* C12. Which walls a combine swallows. The rule is BETWEEN, not inside — see the note on
        `wallBetween` for why a point-in-polygon test answers "no" for exactly these walls. */
{
  const dividing = close([[100, 0], [106, 0], [106, 60], [100, 60]]);   // the wall in the gap
  const outer = close([[-6, 0], [0, 0], [0, 60], [-6, 60]]);            // roomL's far side
  const sets = [[roomL], [roomR(6)]];
  check("the wall between two rooms goes", wallBetween([dividing], sets, 1) === true);
  check("the wall on the outside stays", wallBetween([outer], sets, 1) === false);
  // The threshold is the whole safeguard: a wall that touches both only because the tolerance is
  // absurd is not a wall between them.
  const distant = close([[300, 0], [306, 0], [306, 60], [300, 60]]);
  check("a wall nowhere near either stays", wallBetween([distant], sets, 1) === false);
  check("…and no threshold reaches it", wallBetween([distant], sets, 50) === false);
}

/* C13. Three rooms in a row: the middle two walls go, the two end walls stay. The case Olcay
        described — *"remove the combined walls from wall type"* — with more than one wall in it. */
{
  const a = close([[0, 0], [100, 0], [100, 60], [0, 60]]);
  const b = close([[106, 0], [206, 0], [206, 60], [106, 60]]);
  const c = close([[212, 0], [312, 0], [312, 60], [212, 60]]);
  const sets = [[a], [b], [c]];
  const between1 = close([[100, 0], [106, 0], [106, 60], [100, 60]]);
  const between2 = close([[206, 0], [212, 0], [212, 60], [206, 60]]);
  const endWall = close([[312, 0], [318, 0], [318, 60], [312, 60]]);
  check("the first interior wall goes", wallBetween([between1], sets, 1) === true);
  check("the second interior wall goes", wallBetween([between2], sets, 1) === true);
  check("the end wall stays", wallBetween([endWall], sets, 1) === false);
  // …and the shape they leave behind is one room.
  const r = combineRings([a, b, c], 12);
  check("and the three become one", r.rings.length === 1 && r.joined === 2,
        `${r.rings.length} ring(s)`);
}

/* ══ square engine ═════════════════════════════════════════════════════════════ */

console.log("\nsquare engine");

/** How far the worst edge is from the shape's own grid, in degrees. 0 = perfectly square. */
function worstOffGrid(rings) {
  const th = dominantAngle(rings);
  let worst = 0;
  for (const r of rings) {
    const open = ringOpen(r);
    for (let i = 0; i < open.length; i++) {
      const a = open[i], b = open[(i + 1) % open.length];
      const ang = (Math.atan2(b[1] - a[1], b[0] - a[0]) - th) * 180 / Math.PI;
      const d = ((ang % 90) + 90) % 90;          // 0..90 from the grid
      worst = Math.max(worst, Math.min(d, 90 - d));   // ..and 0..45 to the NEAREST grid line

    }
  }
  return worst;
}

/* Q1. A jittered rectangle comes out square. */
{
  const wonky = close([[0, 0], [100, 3], [97, 60], [-2, 57]]);
  const before = worstOffGrid([wonky]);
  const after = worstOffGrid(squareRings([wonky], 20, 60));
  check("a jittered rectangle starts off-grid", before > 1, `${before.toFixed(2)}°`);
  check("…and comes out square", after < 0.01, `${after.toFixed(4)}°`);
}

/* Q2. ⚠️ It squares to the SHAPE's grid, not to north — a building at an angle stays at its angle. */
{
  const th = 23 * Math.PI / 180, c = Math.cos(th), s = Math.sin(th);
  const rot = ([x, y]) => [x * c - y * s, x * s + y * c];
  const tilted = close([[0, 0], [100, 2], [98, 60], [-1, 58]].map(rot));
  const out = squareRings([tilted], 20, 60);
  check("a tilted rectangle comes out square", worstOffGrid(out) < 0.01,
        `${worstOffGrid(out).toFixed(4)}°`);
  // Against the INPUT's own bearing, not the nominal 23° — the input is deliberately jittered, so
  // its dominant angle is near 23 but not equal to it. What matters is that squaring does not TURN
  // the shape, only straighten it.
  const got = dominantAngle(out) * 180 / Math.PI;
  const want = dominantAngle([tilted]) * 180 / Math.PI;
  const diff = Math.min(Math.abs(got - want), Math.abs(got + 90 - want), Math.abs(got - 90 - want));
  check("…and is not turned in the process", diff < 0.5,
        `bearing ${want.toFixed(2)}° -> ${got.toFixed(2)}°`);
}

/* Q3. ⚠️ A genuine diagonal must SURVIVE — squaring must not invent a right angle. */
{
  const chamfered = close([[0, 0], [80, 0], [100, 20], [100, 60], [0, 60]]);
  const out = squareRings([chamfered], 20, 60)[0];
  const open = ringOpen(out);
  const angs = open.map((a, i) => {
    const b = open[(i + 1) % open.length];
    return Math.abs(Math.atan2(b[1] - a[1], b[0] - a[0]) * 180 / Math.PI);
  });
  check("the 45° chamfer is still a diagonal",
        angs.some((a) => Math.abs(a - 45) < 5), angs.map((a) => a.toFixed(1)).join(", "));
  check("the chamfered shape keeps all its corners", open.length === 5, String(open.length));
}

/* Q4. Squaring keeps the shape recognisable: same corner count, area within a few percent. */
{
  const wonky = close([[0, 0], [100, 3], [97, 60], [-2, 57]]);
  const out = squareRings([wonky], 20, 60);
  const a0 = Math.abs(ringSignedArea(ringOpen(wonky)));
  const a1 = Math.abs(ringSignedArea(ringOpen(out[0])));
  check("corner count is unchanged", ringOpen(out[0]).length === 4, String(ringOpen(out[0]).length));
  check("area is preserved within 5%", Math.abs(a1 - a0) / a0 < 0.05,
        `${a0.toFixed(1)} -> ${a1.toFixed(1)}`);
  for (const r of out) {
    const bad = wellFormed(r);
    check("the squared ring is well formed", !bad, bad || "");
  }
}

/* Q5. Already-square input is a no-op, not a nudge. */
{
  const sq = close([[0, 0], [100, 0], [100, 50], [0, 50]]);
  const out = squareRings([sq], 20, 60)[0];
  let moved = 0;
  ringOpen(sq).forEach((p, i) => {
    moved = Math.max(moved, Math.hypot(p[0] - out[i][0], p[1] - out[i][1]));
  });
  check("a square shape is left alone", moved < 1e-6, `moved ${moved.toExponential(2)}`);
}

/* Q6. A tolerance of 0 changes nothing at all — the guard against a runaway tolerance. */
{
  const wonky = close([[0, 0], [100, 3], [97, 60], [-2, 57]]);
  const out = squareRings([wonky], 0, 60)[0];
  let moved = 0;
  ringOpen(wonky).forEach((p, i) => {
    moved = Math.max(moved, Math.hypot(p[0] - out[i][0], p[1] - out[i][1]));
  });
  check("zero tolerance is a no-op", moved < 1e-9, `moved ${moved}`);
}

/* Q7. Multi-ring features square together, on one shared grid. */
{
  const a = close([[0, 0], [100, 2], [98, 60], [-1, 58]]);
  const b = close([[200, 1], [300, 4], [297, 61], [198, 58]]);
  const out = squareRings([a, b], 20, 60);
  check("both rings come out square", worstOffGrid(out) < 0.01, `${worstOffGrid(out).toFixed(4)}°`);
  check("both rings survive", out.length === 2, String(out.length));
}

/* ══ focus engine ══════════════════════════════════════════════════════════════
   Selecting a feature must NOT change the zoom (Olcay, 2026-08-16: *"respect the user's zoom
   choice but center it if it's off screen"*), so the whole decision is "does the camera move at
   all, and if so by how much" — and the answer that matters most is `null`. */

console.log("\nfocus engine");

const M = FOCUS_MARGIN;
/** A 1440×900 map with no panel, and the same with the 384px properties panel open. */
const bare = focusView(1440, 900, 0);
const withPanel = focusView(1440, 900, 384);
const at = (x, y, w, h) => ({ x0: x, x1: x + w, y0: y, y1: y + h });

/* F1. The whole point: a feature you can already see does not move the camera. */
{
  check("a feature in the middle does not move the map",
        focusPan(at(600, 400, 120, 90), bare) === null);
  // Right up against the margin, and still left alone — the test is inclusive on purpose, or a
  // feature that has JUST been centred would be nudged again by the next click.
  check("a feature exactly on the margin is left alone",
        focusPan(at(M, M, 100, 100), bare) === null);
}

/* F2. Off screen, and it comes back to the middle of the map you can SEE. */
{
  const p = focusPan(at(2000, 400, 100, 100), bare);
  check("a feature off to the right pans", !!p);
  // Its centre is at x=2050; the visible centre is 720. Nothing about zoom enters into it.
  check("…by exactly the offset to the visible centre", p && Math.abs(p[0] - (2050 - 720)) < 1e-9,
        p ? String(p[0]) : "null");
  check("…and not vertically, since it was already level",
        p && Math.abs(p[1] - (450 - 450)) < 1e-9, p ? String(p[1]) : "null");
  check("a feature above the top pans too", !!focusPan(at(600, -500, 100, 100), bare));
}

/* F3. ⚠️ One corner poking out is still off screen. The margin is what stops this being a nuisance
       — a shape merely near the edge is fine; one crossing the margin is not. */
{
  check("a feature straddling the right edge pans",
        !!focusPan(at(1380, 400, 100, 100), bare));
  check("a feature comfortably inside does not",
        focusPan(at(1200, 400, 100, 100), bare) === null);
}

/* F4. The properties panel is not map you can use, so "centre" means centre of what is left. */
{
  const p = focusPan(at(1000, 400, 60, 60), withPanel);
  // The panel starts at 1440-384=1056, so the usable strip is 48..1008 and its centre is 528.
  check("with the panel open a feature under it is moved out", !!p);
  check("…to the centre of the map that is still visible",
        p && Math.abs(p[0] - (1030 - 528)) < 1e-9, p ? String(p[0]) : "null");
  // The same feature, same place, with no panel: comfortably visible and nothing happens.
  check("…and the very same feature is fine without the panel",
        focusPan(at(1000, 400, 60, 60), bare) === null);
}

/* F5. ⚠️ A feature too big to fit is judged on its CENTRE. Containment would say "not visible"
       for a concourse every single time, and pan on every click — including the clicks where you
       were already looking straight at it. */
{
  const huge = at(-2000, -1000, 6000, 3000);       // far larger than the viewport, centred on it
  check("a feature larger than the map does not pan when you are inside it",
        focusPan(huge, bare) === null);
  const away = at(-6000, -1000, 6000, 3000);       // same size, its centre now off to the left
  check("…but does when its centre has gone off screen", !!focusPan(away, bare));
}

/* F6. A panel wider than the map leaves nothing to centre into, and saying so beats dividing by a
       negative width and panning somewhere arbitrary. */
{
  check("no usable map means no view", focusView(300, 900, 400) === null);
  check("…and no pan", focusPan(at(0, 0, 10, 10), focusView(300, 900, 400)) === null);
}

/* ══ box engine ════════════════════════════════════════════════════════════════
   The transform box hugs the SHAPE's grid, not the screen's (Olcay, 2026-08-16: *"Can we hug the
   geometry much better instead of putting the control points relative to the view?"*). The claim
   is a measurement, so these measure it. */

console.log("\nbox engine");

const rot = (pts, deg, ox = 0, oy = 0) => {
  const a = (deg * Math.PI) / 180, c = Math.cos(a), s = Math.sin(a);
  return pts.map(([x, y]) => [
    ox + (x - ox) * c - (y - oy) * s,
    oy + (x - ox) * s + (y - oy) * c,
  ]);
};
/** The screen-aligned box, i.e. exactly what this replaced. */
const aabbArea = (pts) => {
  const xs = pts.map((p) => p[0]), ys = pts.map((p) => p[1]);
  return (Math.max(...xs) - Math.min(...xs)) * (Math.max(...ys) - Math.min(...ys));
};
const side = (a, b) => Math.hypot(b[0] - a[0], b[1] - a[1]);

/* B1. Square to the screen, the box is the bounding box — the case that already worked. */
{
  const r = [[0, 0], [200, 0], [200, 100], [0, 100]];
  const b = orientedBox(r, 0, 0, 0);
  check("an unrotated box is 200 wide", Math.abs(b.w - 200) < 1e-9, String(b.w));
  check("…and 100 high", Math.abs(b.h - 100) < 1e-9, String(b.h));
  check("…centred on the shape", Math.abs(b.cx - 100) < 1e-9 && Math.abs(b.cy - 50) < 1e-9,
        `${b.cx}, ${b.cy}`);
  check("…with its corners in clockwise order from the top-left",
        b.corners[0][0] === 0 && b.corners[0][1] === 0 && b.corners[2][0] === 200,
        JSON.stringify(b.corners));
}

/* B2. Padding is applied in the BOX's frame, so it is even around the shape rather than around
       the screen — the difference that makes a rotated box hug rather than merely contain. */
{
  const r = [[0, 0], [200, 0], [200, 100], [0, 100]];
  const b = orientedBox(r, 0, 12, 0);
  check("padding widens both sides", Math.abs(b.w - 224) < 1e-9, String(b.w));
  check("…and both ends", Math.abs(b.h - 124) < 1e-9, String(b.h));
  check("…without moving the centre", Math.abs(b.cx - 100) < 1e-9 && Math.abs(b.cy - 50) < 1e-9);
}

/* B3. ⚠️ THE POINT. A room turned 30° gets a box the size of the ROOM, not the size of its
       screen shadow — which for this one is nearly twice the area. */
{
  const room = rot([[0, 0], [200, 0], [200, 100], [0, 100]], 30, 100, 50);
  const b = orientedBox(room, (30 * Math.PI) / 180, 0, 0);
  check("a 30° room still measures 200 across", Math.abs(b.w - 200) < 1e-6, String(b.w));
  check("…and 100 deep", Math.abs(b.h - 100) < 1e-6, String(b.h));
  const hugged = b.w * b.h, screenBox = aabbArea(room);
  check("…and the screen-aligned box it replaced was far bigger",
        screenBox > hugged * 1.6, `hugged ${hugged.toFixed(0)}, screen ${screenBox.toFixed(0)}`);
  // Every corner of the room is ON the box, not somewhere inside it.
  for (const p of room) {
    const near = b.corners.some((q) => side(p, q) < 1e-6);
    check("…and each of the room's corners is a box corner", near, JSON.stringify(p));
  }
}

/* B4. The knob comes off the box's own top edge, not off the screen's up. */
{
  const room = rot([[0, 0], [200, 0], [200, 100], [0, 100]], 30, 100, 50);
  const b = orientedBox(room, (30 * Math.PI) / 180, 0, 26);
  check("the knob stands 26 off the top edge", Math.abs(side(b.topMid, b.knob) - 26) < 1e-6,
        String(side(b.topMid, b.knob)));
  // Perpendicular to the top edge: the stem dotted with that edge is zero.
  const ex = b.corners[1][0] - b.corners[0][0], ey = b.corners[1][1] - b.corners[0][1];
  const sx = b.knob[0] - b.topMid[0], sy = b.knob[1] - b.topMid[1];
  check("…square to it", Math.abs(ex * sx + ey * sy) < 1e-6, String(ex * sx + ey * sy));
  check("…and away from the shape, not into it",
        side(b.knob, [b.cx, b.cy]) > side(b.topMid, [b.cx, b.cy]));
}

/* B5. ⚠️ The wrap. A grid angle is modulo 90°, so without unwrapping the box flips — and the
       rotate knob teleports to another edge — as a shape turns past 45°. */
{
  const Q = Math.PI / 2;
  check("the first angle is taken as it comes", unwrapGrid(0.3, undefined) === 0.3);
  // Raw jumped from +44° to -44°; the continuous answer is +46°, not a 90° leap.
  const raw = (-44 * Math.PI) / 180, prev = (44 * Math.PI) / 180;
  const out = unwrapGrid(raw, prev);
  check("a wrap past 45° stays continuous", Math.abs(out - (46 * Math.PI) / 180) < 1e-9,
        `${((out * 180) / Math.PI).toFixed(2)}°`);
  check("…and is still the same grid", Math.abs(((out - raw) % Q)) < 1e-9);
  check("no wrap leaves it alone", Math.abs(unwrapGrid(0.1, 0.12) - 0.1) < 1e-9);
  // Several turns in, it keeps following rather than snapping back to the principal branch.
  check("it follows a shape round more than one quarter turn",
        Math.abs(unwrapGrid(0.05, 3 * Q + 0.05) - (3 * Q + 0.05)) < 1e-9);
}

/* B6. The cursor points along the handle, since the box's corners no longer have fixed compasses. */
{
  check("a handle down-right is the nwse diagonal", geomResizeCursor(10, 10) === "nwse");
  check("a handle down-left is the nesw diagonal", geomResizeCursor(-10, 10) === "nesw");
  check("a handle straight out to the side is ew", geomResizeCursor(10, 0) === "ew");
  check("a handle straight up is ns", geomResizeCursor(0, -10) === "ns");
  // Double-headed: opposite corners of a box must offer the same arrow.
  check("opposite corners agree", geomResizeCursor(10, 10) === geomResizeCursor(-10, -10));
  check("…on the other diagonal too", geomResizeCursor(-10, 10) === geomResizeCursor(10, -10));
}

/* ── verdict ──────────────────────────────────────────────────────────────── */

console.log(failures
  ? `\n${failures} of ${checks} checks FAILED`
  : `\n${checks} checks passed`);
process.exit(failures ? 1 : 0);
