/**
 * The map shell's geometry engines, under test — MAP-566.
 *
 * Three of them: the polygon SPLIT, the SNAP index, and the SQUARE (Straighten) pass. All three
 * live inside `public/map/index.html` between marker comments, and all three are extracted from it
 * rather than copied here, so what is tested is what ships.
 *
 * `public/map/index.html` is a script tag, not a module, so there is nothing to import. Rather than
 * copy the algorithm here — where it would rot the moment somebody fixed a bug in the real one —
 * this extracts the code BETWEEN THE MARKERS out of that file, writes it out as a module, and
 * imports it. The code under test is therefore literally the code that ships; delete the markers
 * and this fails loudly rather than quietly testing a stale copy.
 *
 *     node scratch/geometry.test.mjs
 *
 * Plain screen-space arithmetic throughout, so no map, no DOM, no browser.
 */
import { readFileSync, writeFileSync, unlinkSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const src = readFileSync(join(here, "..", "public", "map", "index.html"), "utf8");

/** Every marker-delimited engine in the map shell, in the order they must be defined. */
const BLOCKS = ["SPLIT-ENGINE", "SNAP-ENGINE", "SQUARE-ENGINE"];
const engine = BLOCKS.map((name) => {
  const from = src.indexOf(`/* ${name}-START`);
  const to = src.indexOf(`/* ${name}-END */`);
  if (from < 0 || to < 0) {
    console.error(`could not find the ${name} markers in public/map/index.html`);
    process.exit(1);
  }
  return src.slice(src.indexOf("*/", from) + 2, to);
}).join("\n");

const generated = join(here, "geometry.generated.mjs");
writeFileSync(
  generated,
  `// GENERATED by geometry.test.mjs from public/map/index.html — do not edit, do not commit.\n` +
    `${engine}\nexport { splitRingsByLine, ringSignedArea, ringOpen,\n` +
      `  segClosest, buildSnapIndex, snapQuery, dominantAngle, squareRings };\n`,
);

let mod;
try {
  mod = await import(pathToFileURL(generated).href);
} finally {
  unlinkSync(generated);
}
const {
  splitRingsByLine, ringSignedArea, ringOpen,
  segClosest, buildSnapIndex, snapQuery, dominantAngle, squareRings,
} = mod;

/* ── helpers ──────────────────────────────────────────────────────────────── */

let failures = 0;
let checks = 0;

function check(name, cond, detail) {
  checks++;
  if (cond) return;
  failures++;
  console.error(`  ✗ ${name}${detail ? ` — ${detail}` : ""}`);
}

const area = (ring) => Math.abs(ringSignedArea(ringOpen(ring)));
const areaOf = (rings) => rings.reduce((n, r) => n + area(r), 0);

/** Is this a ring anyone can trust? Closed, at least a triangle, no repeated neighbours. */
function wellFormed(ring) {
  if (ring.length < 4) return "fewer than 3 distinct points";
  const first = ring[0], last = ring[ring.length - 1];
  if (first[0] !== last[0] || first[1] !== last[1]) return "not closed";
  for (const [x, y] of ring) if (!Number.isFinite(x) || !Number.isFinite(y)) return "non-finite point";
  const open = ringOpen(ring);
  for (let i = 0; i < open.length; i++) {
    const p = open[i], q = open[(i + 1) % open.length];
    if (Math.hypot(p[0] - q[0], p[1] - q[1]) < 1e-9) return `repeated point at ${i}`;
  }
  if (Math.abs(ringSignedArea(open)) < 1e-9) return "zero area";
  return null;
}

/**
 * The invariants every successful cut must satisfy, whatever the shape:
 * both halves exist, every ring is well formed, and the pieces add back up to the original.
 */
function expectSplit(name, rings, a, b, { leftRings, rightRings }) {
  const res = splitRingsByLine(rings, a, b);
  if (!res.ok) {
    check(name, false, `expected a split, was refused with "${res.reason}"`);
    return null;
  }
  check(`${name} · left ring count`, res.left.length === leftRings,
        `expected ${leftRings}, got ${res.left.length}`);
  check(`${name} · right ring count`, res.right.length === rightRings,
        `expected ${rightRings}, got ${res.right.length}`);
  for (const [side, list] of [["left", res.left], ["right", res.right]]) {
    list.forEach((r, i) => {
      const bad = wellFormed(r);
      check(`${name} · ${side}[${i}] well formed`, !bad, bad || "");
    });
  }
  // Area is the honest check: a cut neither creates nor destroys floor.
  const before = areaOf(rings);
  const after = areaOf(res.left) + areaOf(res.right);
  check(`${name} · area conserved`, Math.abs(before - after) < before * 1e-9,
        `before ${before.toFixed(6)}, after ${after.toFixed(6)}`);
  // Provenance: the caller needs to know which input ring each piece came from to keep track of
  // what is new, and it cannot recover that from two flattened lists.
  check(`${name} · every piece says where it came from`,
        res.leftFrom.length === res.left.length &&
          res.rightFrom.length === res.right.length &&
          [...res.leftFrom, ...res.rightFrom].every((j) => j >= 0 && j < rings.length),
        `leftFrom ${JSON.stringify(res.leftFrom)}, rightFrom ${JSON.stringify(res.rightFrom)}`);
  check(`${name} · every input ring is accounted for`,
        rings.every((_, j) => typeof res.wasCut[j] === "boolean" &&
                              [...res.leftFrom, ...res.rightFrom].includes(j)),
        `wasCut ${JSON.stringify(res.wasCut)}`);
  return res;
}

function expectNoSplit(name, rings, a, b, reason) {
  const res = splitRingsByLine(rings, a, b);
  check(name, !res.ok && res.reason === reason,
        res.ok ? `split into ${res.left.length}/${res.right.length}` : `refused with "${res.reason}"`);
}

const close = (pts) => [...pts.map((p) => p.slice()), pts[0].slice()];

/* ── the shapes ───────────────────────────────────────────────────────────── */

// A plain 10×10 room.
const SQUARE = close([[0, 0], [10, 0], [10, 10], [0, 10]]);

// A U, opening upward: arms at x∈[0,3] and x∈[7,10], joined by a base at y∈[0,3].
// The shape MAP-566 called out by name — a horizontal cut across both arms must give three pieces.
const U = close([
  [0, 0], [10, 0], [10, 10], [7, 10], [7, 3], [3, 3], [3, 10], [0, 10],
]);

// An L.
const L = close([[0, 0], [10, 0], [10, 4], [4, 4], [4, 10], [0, 10]]);

// A comb with three teeth — six crossings' worth of concavity, to push the chord pairing.
const COMB = close([
  [0, 0], [12, 0], [12, 10], [10, 10], [10, 4], [8, 4], [8, 10],
  [6, 10], [6, 4], [4, 4], [4, 10], [2, 10], [2, 4], [0, 4],
]);

console.log("split engine");

/* 1. The easy one, and the one a convex-only implementation also gets right. */
expectSplit("square, cut across the middle", [SQUARE], [-5, 5], [15, 5],
            { leftRings: 1, rightRings: 1 });

/* 2. Diagonal — the cut hits two edges at an angle, not at right angles. */
expectSplit("square, diagonal cut", [SQUARE], [-5, -4], [15, 6],
            { leftRings: 1, rightRings: 1 });

/* 3. The recorded bar: a concave U cut across BOTH arms. Four crossings, two chords. Above the cut
      the arms are two separate pieces; below it the base is one. A convex-only implementation
      joins the arm tips through thin air and mangles the floor — this is the case that catches it. */
{
  const res = expectSplit("U, cut across both arms", [U], [-5, 6], [15, 6],
                          { leftRings: 2, rightRings: 1 });
  if (res) {
    // The two upper pieces must be the arm TIPS: 3 wide, 4 tall.
    const tips = res.left.map(area).sort((x, y) => x - y);
    check("U · arm tips are 3×4", tips.every((t) => Math.abs(t - 12) < 1e-9),
          `got ${tips.map((t) => t.toFixed(3)).join(", ")}`);
    // …and nothing spans the gap between them.
    for (const r of res.left) {
      const xs = ringOpen(r).map((p) => p[0]);
      const span = Math.max(...xs) - Math.min(...xs);
      check("U · no piece spans the gap", span <= 3 + 1e-9, `span ${span.toFixed(3)}`);
    }
  }
}

/* 4. The same U, cut low enough to miss the arms — one crossing pair, two ordinary pieces. */
expectSplit("U, cut below the arms", [U], [-5, 1.5], [15, 1.5],
            { leftRings: 1, rightRings: 1 });

/* 5. A vertical cut down the U's left arm. */
expectSplit("U, cut down one arm", [U], [1.5, -5], [1.5, 15],
            { leftRings: 1, rightRings: 1 });

/* 6. L, cut either way through the reflex corner region. */
expectSplit("L, horizontal cut", [L], [-5, 2], [15, 2], { leftRings: 1, rightRings: 1 });
expectSplit("L, vertical cut", [L], [2, -5], [2, 15], { leftRings: 1, rightRings: 1 });

/* 7. Three teeth: a cut across all of them yields three tips on one side, the spine on the other.
      Six crossings, three chords — the pairing has to get every one of them right. */
{
  const res = expectSplit("comb, cut across all three teeth", [COMB], [-5, 7], [20, 7],
                          { leftRings: 3, rightRings: 1 });
  if (res) {
    const tips = res.left.map(area);
    check("comb · every tooth is 2×3", tips.every((t) => Math.abs(t - 6) < 1e-9),
          `got ${tips.map((t) => t.toFixed(3)).join(", ")}`);
  }
}

/* 8. Straight through two opposite VERTICES. Both are already on the line, so nothing is inserted
      and the whole thing rests on the run/crossing classification. */
expectSplit("square, corner to corner through the vertices", [SQUARE], [-5, -5], [15, 15],
            { leftRings: 1, rightRings: 1 });

/* 9. A cut that only TOUCHES a corner — `y = x + 10` rests on (0,10) with the square below it.
      The classic trap: one on-line vertex, no crossing, and an implementation that counts touches
      produces a zero-area second piece and calls it a room. */
expectNoSplit("square, line grazing a corner", [SQUARE], [-5, 5], [5, 15], "miss");

/* 10. A cut running ALONG an edge — a whole collinear run on the line, still not a cut. */
expectNoSplit("square, line along the bottom edge", [SQUARE], [-5, 0], [15, 0], "miss");

/* 11. Misses entirely. */
expectNoSplit("square, line well clear", [SQUARE], [-5, 20], [15, 20], "miss");

/* 12. A degenerate cut — the two clicks landed on the same pixel. */
expectNoSplit("square, zero-length cut", [SQUARE], [5, 5], [5, 5], "miss");

/* 12b. ⚠️ The degenerate this suite was written to find. A cut laid exactly along the U's inner
        edge crosses at x=0 and x=10, but the stretch between x=3 and x=7 is OUTSIDE the shape —
        so pairing those two crossings joins the arms straight through the notch. Area still
        balances, which is exactly why area alone is not enough of a check. It must be refused. */
expectNoSplit("U, cut exactly along the inner edge", [U], [-5, 3], [15, 3], "tangent");

/* 12c. …and the same refusal for a cut that crosses cleanly AND grazes the reflex corner on the
        way. `y = 8 − x` passes through the L's inner corner (4,4) with both its neighbours above
        the line, and crosses the outline properly at (8,0) and (0,8). Two crossings and one touch:
        pair the crossings and you get a plausible-looking piece bounded by a line that never
        entered the shape. */
expectNoSplit("L, cut crossing but grazing the reflex corner", [L], [-2, 10], [12, -4], "tangent");

/* 12d. The collinear run that IS a crossing must still work — an edge lying along the cut while
        the ring passes from one side to the other. Nothing to refuse here; the run's far end
        carries the crossing and the on-line points add no area to whichever piece they land in. */
{
  const STEP = close([[0, 0], [10, 0], [10, 5], [6, 5], [6, 10], [0, 10]]);
  const res = expectSplit("step, cut along the horizontal edge", [STEP], [-5, 5], [15, 5],
                          { leftRings: 1, rightRings: 1 });
  if (res) {
    check("step · pieces are 50 and 30",
          Math.abs(areaOf(res.right) - 50) < 1e-9 && Math.abs(areaOf(res.left) - 30) < 1e-9,
          `got ${areaOf(res.right).toFixed(3)} and ${areaOf(res.left).toFixed(3)}`);
  }
}

/* 13. A cut down the U's notch separates the two arms, and must not invent geometry in the gap. */
expectSplit("U, cut down the notch", [U], [5, -5], [5, 15], { leftRings: 1, rightRings: 1 });

/* 14. A feature that is already two rings. The line crosses one and misses the other — the missed
       ring must travel whole to its own side rather than vanish. */
{
  const far = close([[20, 0], [30, 0], [30, 10], [20, 10]]);
  const res = expectSplit("two rings, cut through one", [SQUARE, far], [5, -5], [5, 15],
                          { leftRings: 1, rightRings: 2 });
  if (res) {
    check("two rings · the untouched ring survives whole",
          res.right.some((r) => Math.abs(area(r) - 100) < 1e-9),
          `right areas ${res.right.map((r) => area(r).toFixed(1)).join(", ")}`);
    // The caller mints new piece ids for cut rings only, so this distinction has to be right or an
    // untouched ring is announced as a brand-new piece of a feature nobody split.
    check("two rings · only the crossed ring is marked cut",
          res.wasCut[0] === true && res.wasCut[1] === false,
          `wasCut ${JSON.stringify(res.wasCut)}`);
  }
}

/* 15. Both rings cut by the same line. */
{
  const far = close([[20, 0], [30, 0], [30, 10], [20, 10]]);
  expectSplit("two rings, cut through both", [SQUARE, far], [-5, 5], [40, 5],
              { leftRings: 2, rightRings: 2 });
}

/* 16. Winding must not matter — the same square, wound the other way. */
expectSplit("square wound clockwise", [close([[0, 0], [0, 10], [10, 10], [10, 0]])],
            [-5, 5], [15, 5], { leftRings: 1, rightRings: 1 });

/* 17. Direction of the cut must not matter either: a→b and b→a swap the labels, nothing else. */
{
  const ab = splitRingsByLine([U], [-5, 6], [15, 6]);
  const ba = splitRingsByLine([U], [15, 6], [-5, 6]);
  check("cut direction only swaps the sides",
        ab.ok && ba.ok && ab.left.length === ba.right.length && ab.right.length === ba.left.length,
        ab.ok && ba.ok
          ? `${ab.left.length}/${ab.right.length} vs ${ba.left.length}/${ba.right.length}`
          : "refused");
}

/* 18. Real-world scale. The tolerance is relative to the cut's length, so a long cut across a
       small shape must still behave — this is the one that catches an absolute epsilon. */
expectSplit("long cut across a small shape",
            [close([[100, 100], [104, 100], [104, 104], [100, 104]])],
            [-5000, 102], [5000, 102], { leftRings: 1, rightRings: 1 });


/* ══ snap engine ═══════════════════════════════════════════════════════════════ */

console.log("\nsnap engine");

/* S1. The nearest point on a segment, including past both ends. */
{
  const near = (n, got, want) => check(n, Math.hypot(got[0]-want[0], got[1]-want[1]) < 1e-9,
    `got ${got}, want ${want}`);
  near("foot lands mid-segment", segClosest(5, 5, 0, 0, 10, 0), [5, 0]);
  near("clamps past the start", segClosest(-5, 3, 0, 0, 10, 0), [0, 0]);
  near("clamps past the end", segClosest(99, 3, 0, 0, 10, 0), [10, 0]);
  near("a zero-length segment is its own point", segClosest(4, 4, 7, 7, 7, 7), [7, 7]);
  near("works on a diagonal", segClosest(0, 10, 0, 0, 10, 10), [5, 5]);
}

/* S2. A corner wins a near-tie — meeting a corner has to stay easy. */
{
  const idx = buildSnapIndex([[100, 100]], [[80, 96, 200, 96]], 24);
  const hit = snapQuery(idx, 100, 99, 10);   // corner 1px away, edge 3px away
  check("a corner wins a near-tie", hit && hit.kind === "corner",
        hit ? hit.kind + " @" + hit.d.toFixed(2) : "null");
}

/* S2b. ⚠️ THE REGRESSION. A corner in range used to win outright, so in floor-plan geometry — where
        some corner is nearly always within the radius — the edge was found and then always lost.
        Edge snapping was unreachable in exactly the geometry it was built for. Here the corner is
        9px off and the edge 1px: the edge is plainly what you were aiming at. */
{
  const idx = buildSnapIndex([[100, 91]], [[0, 100, 400, 100]], 24);
  const hit = snapQuery(idx, 100, 99, 10);
  check("a clearly closer edge beats a distant corner", hit && hit.kind === "edge",
        hit ? `${hit.kind} @${hit.d.toFixed(2)}` : "null");
}

/* S2c. The bias is the whole rule: just inside it the corner holds, just outside it the edge takes
        over. Pinned so the constant cannot drift without a test noticing. */
{
  const edge = [[0, 100, 400, 100]];
  const held = snapQuery(buildSnapIndex([[100, 96]], edge, 24), 100, 100, 10); // corner 4, edge 0
  check("corner holds inside the bias", held && held.kind === "corner",
        held ? held.kind : "null");
  const lost = snapQuery(buildSnapIndex([[100, 94]], edge, 24), 100, 100, 10); // corner 6, edge 0
  check("…and yields outside it", lost && lost.kind === "edge", lost ? lost.kind : "null");
}

/* S3. An edge is found when no corner is in range — the case that did not exist before. */
{
  const idx = buildSnapIndex([[500, 500]], [[0, 200, 400, 200]], 24);
  const hit = snapQuery(idx, 210, 206, 10);
  check("snaps onto an edge", hit && hit.kind === "edge", hit ? hit.kind : "null");
  check("edge snap is the perpendicular foot",
        hit && Math.abs(hit.x - 210) < 1e-9 && Math.abs(hit.y - 200) < 1e-9,
        hit ? `${hit.x}, ${hit.y}` : "null");
}

/* S4. Nothing within the radius means no snap — a tool that always snaps is unusable. */
{
  const idx = buildSnapIndex([[0, 0]], [[0, 200, 400, 200]], 24);
  check("out of range returns null", snapQuery(idx, 210, 260, 10) === null);
  check("a null index never throws", snapQuery(null, 1, 2, 10) === null);
}

/* S5. The grid must not change the answer — the index is an optimisation, not a behaviour.
       Brute force over random data, against the same query. */
{
  let mismatches = 0;
  let seed = 12345;
  const rnd = () => (seed = (seed * 1103515245 + 12345) % 2147483648) / 2147483648;
  const verts = Array.from({ length: 400 }, () => [rnd() * 2000, rnd() * 2000]);
  const segs = Array.from({ length: 400 }, () => {
    const x = rnd() * 2000, y = rnd() * 2000;
    return [x, y, x + (rnd() - 0.5) * 300, y + (rnd() - 0.5) * 300];
  });
  const idx = buildSnapIndex(verts, segs, 24);
  for (let i = 0; i < 500; i++) {
    const px = rnd() * 2000, py = rnd() * 2000, R = 10;
    // the honest O(n) answer, with the same biased corner-beats-edge rule
    let bv = null, bvd = R, be = null, bed = R;
    for (const v of verts) { const d = Math.hypot(v[0]-px, v[1]-py); if (d < bvd) { bvd = d; bv = v; } }
    for (const sg of segs) {
      const q = segClosest(px, py, sg[0], sg[1], sg[2], sg[3]);
      const d = Math.hypot(q[0]-px, q[1]-py); if (d < bed) { bed = d; be = q; }
    }
    const BIAS = 5;   // must match SNAP_CORNER_BIAS in the shell
    const want = bv && (!be || bvd <= bed + BIAS) ? { kind: "corner", d: bvd }
               : be ? { kind: "edge", d: bed } : null;
    const got = snapQuery(idx, px, py, R);
    const same = (!want && !got) ||
      (want && got && want.kind === got.kind && Math.abs(want.d - got.d) < 1e-9);
    if (!same) mismatches++;
  }
  check("the index agrees with brute force on 500 random queries", mismatches === 0,
        `${mismatches} disagreed`);
}

/* ══ square engine ═════════════════════════════════════════════════════════════ */

console.log("\nsquare engine");

/** How far the worst edge is from the shape's own grid, in degrees. 0 = perfectly square. */
function worstOffGrid(rings) {
  const th = dominantAngle(rings);
  let worst = 0;
  for (const r of rings) {
    const open = ringOpen(r);
    for (let i = 0; i < open.length; i++) {
      const a = open[i], b = open[(i + 1) % open.length];
      const ang = (Math.atan2(b[1] - a[1], b[0] - a[0]) - th) * 180 / Math.PI;
      const d = ((ang % 90) + 90) % 90;          // 0..90 from the grid
      worst = Math.max(worst, Math.min(d, 90 - d));   // ..and 0..45 to the NEAREST grid line

    }
  }
  return worst;
}

/* Q1. A jittered rectangle comes out square. */
{
  const wonky = close([[0, 0], [100, 3], [97, 60], [-2, 57]]);
  const before = worstOffGrid([wonky]);
  const after = worstOffGrid(squareRings([wonky], 20, 60));
  check("a jittered rectangle starts off-grid", before > 1, `${before.toFixed(2)}°`);
  check("…and comes out square", after < 0.01, `${after.toFixed(4)}°`);
}

/* Q2. ⚠️ It squares to the SHAPE's grid, not to north — a building at an angle stays at its angle. */
{
  const th = 23 * Math.PI / 180, c = Math.cos(th), s = Math.sin(th);
  const rot = ([x, y]) => [x * c - y * s, x * s + y * c];
  const tilted = close([[0, 0], [100, 2], [98, 60], [-1, 58]].map(rot));
  const out = squareRings([tilted], 20, 60);
  check("a tilted rectangle comes out square", worstOffGrid(out) < 0.01,
        `${worstOffGrid(out).toFixed(4)}°`);
  // Against the INPUT's own bearing, not the nominal 23° — the input is deliberately jittered, so
  // its dominant angle is near 23 but not equal to it. What matters is that squaring does not TURN
  // the shape, only straighten it.
  const got = dominantAngle(out) * 180 / Math.PI;
  const want = dominantAngle([tilted]) * 180 / Math.PI;
  const diff = Math.min(Math.abs(got - want), Math.abs(got + 90 - want), Math.abs(got - 90 - want));
  check("…and is not turned in the process", diff < 0.5,
        `bearing ${want.toFixed(2)}° -> ${got.toFixed(2)}°`);
}

/* Q3. ⚠️ A genuine diagonal must SURVIVE — squaring must not invent a right angle. */
{
  const chamfered = close([[0, 0], [80, 0], [100, 20], [100, 60], [0, 60]]);
  const out = squareRings([chamfered], 20, 60)[0];
  const open = ringOpen(out);
  const angs = open.map((a, i) => {
    const b = open[(i + 1) % open.length];
    return Math.abs(Math.atan2(b[1] - a[1], b[0] - a[0]) * 180 / Math.PI);
  });
  check("the 45° chamfer is still a diagonal",
        angs.some((a) => Math.abs(a - 45) < 5), angs.map((a) => a.toFixed(1)).join(", "));
  check("the chamfered shape keeps all its corners", open.length === 5, String(open.length));
}

/* Q4. Squaring keeps the shape recognisable: same corner count, area within a few percent. */
{
  const wonky = close([[0, 0], [100, 3], [97, 60], [-2, 57]]);
  const out = squareRings([wonky], 20, 60);
  const a0 = Math.abs(ringSignedArea(ringOpen(wonky)));
  const a1 = Math.abs(ringSignedArea(ringOpen(out[0])));
  check("corner count is unchanged", ringOpen(out[0]).length === 4, String(ringOpen(out[0]).length));
  check("area is preserved within 5%", Math.abs(a1 - a0) / a0 < 0.05,
        `${a0.toFixed(1)} -> ${a1.toFixed(1)}`);
  for (const r of out) {
    const bad = wellFormed(r);
    check("the squared ring is well formed", !bad, bad || "");
  }
}

/* Q5. Already-square input is a no-op, not a nudge. */
{
  const sq = close([[0, 0], [100, 0], [100, 50], [0, 50]]);
  const out = squareRings([sq], 20, 60)[0];
  let moved = 0;
  ringOpen(sq).forEach((p, i) => {
    moved = Math.max(moved, Math.hypot(p[0] - out[i][0], p[1] - out[i][1]));
  });
  check("a square shape is left alone", moved < 1e-6, `moved ${moved.toExponential(2)}`);
}

/* Q6. A tolerance of 0 changes nothing at all — the guard against a runaway tolerance. */
{
  const wonky = close([[0, 0], [100, 3], [97, 60], [-2, 57]]);
  const out = squareRings([wonky], 0, 60)[0];
  let moved = 0;
  ringOpen(wonky).forEach((p, i) => {
    moved = Math.max(moved, Math.hypot(p[0] - out[i][0], p[1] - out[i][1]));
  });
  check("zero tolerance is a no-op", moved < 1e-9, `moved ${moved}`);
}

/* Q7. Multi-ring features square together, on one shared grid. */
{
  const a = close([[0, 0], [100, 2], [98, 60], [-1, 58]]);
  const b = close([[200, 1], [300, 4], [297, 61], [198, 58]]);
  const out = squareRings([a, b], 20, 60);
  check("both rings come out square", worstOffGrid(out) < 0.01, `${worstOffGrid(out).toFixed(4)}°`);
  check("both rings survive", out.length === 2, String(out.length));
}

/* ── verdict ──────────────────────────────────────────────────────────────── */

console.log(failures
  ? `\n${failures} of ${checks} checks FAILED`
  : `\n${checks} checks passed`);
process.exit(failures ? 1 : 0);
