/**
 * The split engine, under test — MAP-566.
 *
 * `public/map/index.html` is a script tag, not a module, so there is nothing to import. Rather than
 * copy the algorithm here — where it would rot the moment somebody fixed a bug in the real one —
 * this extracts the code BETWEEN THE MARKERS out of that file, writes it out as a module, and
 * imports it. The code under test is therefore literally the code that ships; delete the markers
 * and this fails loudly rather than quietly testing a stale copy.
 *
 *     node scratch/split-engine.test.mjs
 *
 * Plain screen-space arithmetic throughout, so no map, no DOM, no browser.
 */
import { readFileSync, writeFileSync, unlinkSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const src = readFileSync(join(here, "..", "public", "map", "index.html"), "utf8");

const from = src.indexOf("/* SPLIT-ENGINE-START");
const to = src.indexOf("/* SPLIT-ENGINE-END */");
if (from < 0 || to < 0) {
  console.error("could not find the SPLIT-ENGINE markers in public/map/index.html");
  process.exit(1);
}
const engine = src.slice(src.indexOf("*/", from) + 2, to);

const generated = join(here, "split-engine.generated.mjs");
writeFileSync(
  generated,
  `// GENERATED by split-engine.test.mjs from public/map/index.html — do not edit, do not commit.\n` +
    `${engine}\nexport { splitRingsByLine, ringSignedArea, ringOpen };\n`,
);

let mod;
try {
  mod = await import(pathToFileURL(generated).href);
} finally {
  unlinkSync(generated);
}
const { splitRingsByLine, ringSignedArea, ringOpen } = mod;

/* ── helpers ──────────────────────────────────────────────────────────────── */

let failures = 0;
let checks = 0;

function check(name, cond, detail) {
  checks++;
  if (cond) return;
  failures++;
  console.error(`  ✗ ${name}${detail ? ` — ${detail}` : ""}`);
}

const area = (ring) => Math.abs(ringSignedArea(ringOpen(ring)));
const areaOf = (rings) => rings.reduce((n, r) => n + area(r), 0);

/** Is this a ring anyone can trust? Closed, at least a triangle, no repeated neighbours. */
function wellFormed(ring) {
  if (ring.length < 4) return "fewer than 3 distinct points";
  const first = ring[0], last = ring[ring.length - 1];
  if (first[0] !== last[0] || first[1] !== last[1]) return "not closed";
  for (const [x, y] of ring) if (!Number.isFinite(x) || !Number.isFinite(y)) return "non-finite point";
  const open = ringOpen(ring);
  for (let i = 0; i < open.length; i++) {
    const p = open[i], q = open[(i + 1) % open.length];
    if (Math.hypot(p[0] - q[0], p[1] - q[1]) < 1e-9) return `repeated point at ${i}`;
  }
  if (Math.abs(ringSignedArea(open)) < 1e-9) return "zero area";
  return null;
}

/**
 * The invariants every successful cut must satisfy, whatever the shape:
 * both halves exist, every ring is well formed, and the pieces add back up to the original.
 */
function expectSplit(name, rings, a, b, { leftRings, rightRings }) {
  const res = splitRingsByLine(rings, a, b);
  if (!res.ok) {
    check(name, false, `expected a split, was refused with "${res.reason}"`);
    return null;
  }
  check(`${name} · left ring count`, res.left.length === leftRings,
        `expected ${leftRings}, got ${res.left.length}`);
  check(`${name} · right ring count`, res.right.length === rightRings,
        `expected ${rightRings}, got ${res.right.length}`);
  for (const [side, list] of [["left", res.left], ["right", res.right]]) {
    list.forEach((r, i) => {
      const bad = wellFormed(r);
      check(`${name} · ${side}[${i}] well formed`, !bad, bad || "");
    });
  }
  // Area is the honest check: a cut neither creates nor destroys floor.
  const before = areaOf(rings);
  const after = areaOf(res.left) + areaOf(res.right);
  check(`${name} · area conserved`, Math.abs(before - after) < before * 1e-9,
        `before ${before.toFixed(6)}, after ${after.toFixed(6)}`);
  // Provenance: the caller needs to know which input ring each piece came from to keep track of
  // what is new, and it cannot recover that from two flattened lists.
  check(`${name} · every piece says where it came from`,
        res.leftFrom.length === res.left.length &&
          res.rightFrom.length === res.right.length &&
          [...res.leftFrom, ...res.rightFrom].every((j) => j >= 0 && j < rings.length),
        `leftFrom ${JSON.stringify(res.leftFrom)}, rightFrom ${JSON.stringify(res.rightFrom)}`);
  check(`${name} · every input ring is accounted for`,
        rings.every((_, j) => typeof res.wasCut[j] === "boolean" &&
                              [...res.leftFrom, ...res.rightFrom].includes(j)),
        `wasCut ${JSON.stringify(res.wasCut)}`);
  return res;
}

function expectNoSplit(name, rings, a, b, reason) {
  const res = splitRingsByLine(rings, a, b);
  check(name, !res.ok && res.reason === reason,
        res.ok ? `split into ${res.left.length}/${res.right.length}` : `refused with "${res.reason}"`);
}

const close = (pts) => [...pts.map((p) => p.slice()), pts[0].slice()];

/* ── the shapes ───────────────────────────────────────────────────────────── */

// A plain 10×10 room.
const SQUARE = close([[0, 0], [10, 0], [10, 10], [0, 10]]);

// A U, opening upward: arms at x∈[0,3] and x∈[7,10], joined by a base at y∈[0,3].
// The shape MAP-566 called out by name — a horizontal cut across both arms must give three pieces.
const U = close([
  [0, 0], [10, 0], [10, 10], [7, 10], [7, 3], [3, 3], [3, 10], [0, 10],
]);

// An L.
const L = close([[0, 0], [10, 0], [10, 4], [4, 4], [4, 10], [0, 10]]);

// A comb with three teeth — six crossings' worth of concavity, to push the chord pairing.
const COMB = close([
  [0, 0], [12, 0], [12, 10], [10, 10], [10, 4], [8, 4], [8, 10],
  [6, 10], [6, 4], [4, 4], [4, 10], [2, 10], [2, 4], [0, 4],
]);

console.log("split engine");

/* 1. The easy one, and the one a convex-only implementation also gets right. */
expectSplit("square, cut across the middle", [SQUARE], [-5, 5], [15, 5],
            { leftRings: 1, rightRings: 1 });

/* 2. Diagonal — the cut hits two edges at an angle, not at right angles. */
expectSplit("square, diagonal cut", [SQUARE], [-5, -4], [15, 6],
            { leftRings: 1, rightRings: 1 });

/* 3. The recorded bar: a concave U cut across BOTH arms. Four crossings, two chords. Above the cut
      the arms are two separate pieces; below it the base is one. A convex-only implementation
      joins the arm tips through thin air and mangles the floor — this is the case that catches it. */
{
  const res = expectSplit("U, cut across both arms", [U], [-5, 6], [15, 6],
                          { leftRings: 2, rightRings: 1 });
  if (res) {
    // The two upper pieces must be the arm TIPS: 3 wide, 4 tall.
    const tips = res.left.map(area).sort((x, y) => x - y);
    check("U · arm tips are 3×4", tips.every((t) => Math.abs(t - 12) < 1e-9),
          `got ${tips.map((t) => t.toFixed(3)).join(", ")}`);
    // …and nothing spans the gap between them.
    for (const r of res.left) {
      const xs = ringOpen(r).map((p) => p[0]);
      const span = Math.max(...xs) - Math.min(...xs);
      check("U · no piece spans the gap", span <= 3 + 1e-9, `span ${span.toFixed(3)}`);
    }
  }
}

/* 4. The same U, cut low enough to miss the arms — one crossing pair, two ordinary pieces. */
expectSplit("U, cut below the arms", [U], [-5, 1.5], [15, 1.5],
            { leftRings: 1, rightRings: 1 });

/* 5. A vertical cut down the U's left arm. */
expectSplit("U, cut down one arm", [U], [1.5, -5], [1.5, 15],
            { leftRings: 1, rightRings: 1 });

/* 6. L, cut either way through the reflex corner region. */
expectSplit("L, horizontal cut", [L], [-5, 2], [15, 2], { leftRings: 1, rightRings: 1 });
expectSplit("L, vertical cut", [L], [2, -5], [2, 15], { leftRings: 1, rightRings: 1 });

/* 7. Three teeth: a cut across all of them yields three tips on one side, the spine on the other.
      Six crossings, three chords — the pairing has to get every one of them right. */
{
  const res = expectSplit("comb, cut across all three teeth", [COMB], [-5, 7], [20, 7],
                          { leftRings: 3, rightRings: 1 });
  if (res) {
    const tips = res.left.map(area);
    check("comb · every tooth is 2×3", tips.every((t) => Math.abs(t - 6) < 1e-9),
          `got ${tips.map((t) => t.toFixed(3)).join(", ")}`);
  }
}

/* 8. Straight through two opposite VERTICES. Both are already on the line, so nothing is inserted
      and the whole thing rests on the run/crossing classification. */
expectSplit("square, corner to corner through the vertices", [SQUARE], [-5, -5], [15, 15],
            { leftRings: 1, rightRings: 1 });

/* 9. A cut that only TOUCHES a corner — `y = x + 10` rests on (0,10) with the square below it.
      The classic trap: one on-line vertex, no crossing, and an implementation that counts touches
      produces a zero-area second piece and calls it a room. */
expectNoSplit("square, line grazing a corner", [SQUARE], [-5, 5], [5, 15], "miss");

/* 10. A cut running ALONG an edge — a whole collinear run on the line, still not a cut. */
expectNoSplit("square, line along the bottom edge", [SQUARE], [-5, 0], [15, 0], "miss");

/* 11. Misses entirely. */
expectNoSplit("square, line well clear", [SQUARE], [-5, 20], [15, 20], "miss");

/* 12. A degenerate cut — the two clicks landed on the same pixel. */
expectNoSplit("square, zero-length cut", [SQUARE], [5, 5], [5, 5], "miss");

/* 12b. ⚠️ The degenerate this suite was written to find. A cut laid exactly along the U's inner
        edge crosses at x=0 and x=10, but the stretch between x=3 and x=7 is OUTSIDE the shape —
        so pairing those two crossings joins the arms straight through the notch. Area still
        balances, which is exactly why area alone is not enough of a check. It must be refused. */
expectNoSplit("U, cut exactly along the inner edge", [U], [-5, 3], [15, 3], "tangent");

/* 12c. …and the same refusal for a cut that crosses cleanly AND grazes the reflex corner on the
        way. `y = 8 − x` passes through the L's inner corner (4,4) with both its neighbours above
        the line, and crosses the outline properly at (8,0) and (0,8). Two crossings and one touch:
        pair the crossings and you get a plausible-looking piece bounded by a line that never
        entered the shape. */
expectNoSplit("L, cut crossing but grazing the reflex corner", [L], [-2, 10], [12, -4], "tangent");

/* 12d. The collinear run that IS a crossing must still work — an edge lying along the cut while
        the ring passes from one side to the other. Nothing to refuse here; the run's far end
        carries the crossing and the on-line points add no area to whichever piece they land in. */
{
  const STEP = close([[0, 0], [10, 0], [10, 5], [6, 5], [6, 10], [0, 10]]);
  const res = expectSplit("step, cut along the horizontal edge", [STEP], [-5, 5], [15, 5],
                          { leftRings: 1, rightRings: 1 });
  if (res) {
    check("step · pieces are 50 and 30",
          Math.abs(areaOf(res.right) - 50) < 1e-9 && Math.abs(areaOf(res.left) - 30) < 1e-9,
          `got ${areaOf(res.right).toFixed(3)} and ${areaOf(res.left).toFixed(3)}`);
  }
}

/* 13. A cut down the U's notch separates the two arms, and must not invent geometry in the gap. */
expectSplit("U, cut down the notch", [U], [5, -5], [5, 15], { leftRings: 1, rightRings: 1 });

/* 14. A feature that is already two rings. The line crosses one and misses the other — the missed
       ring must travel whole to its own side rather than vanish. */
{
  const far = close([[20, 0], [30, 0], [30, 10], [20, 10]]);
  const res = expectSplit("two rings, cut through one", [SQUARE, far], [5, -5], [5, 15],
                          { leftRings: 1, rightRings: 2 });
  if (res) {
    check("two rings · the untouched ring survives whole",
          res.right.some((r) => Math.abs(area(r) - 100) < 1e-9),
          `right areas ${res.right.map((r) => area(r).toFixed(1)).join(", ")}`);
    // The caller mints new piece ids for cut rings only, so this distinction has to be right or an
    // untouched ring is announced as a brand-new piece of a feature nobody split.
    check("two rings · only the crossed ring is marked cut",
          res.wasCut[0] === true && res.wasCut[1] === false,
          `wasCut ${JSON.stringify(res.wasCut)}`);
  }
}

/* 15. Both rings cut by the same line. */
{
  const far = close([[20, 0], [30, 0], [30, 10], [20, 10]]);
  expectSplit("two rings, cut through both", [SQUARE, far], [-5, 5], [40, 5],
              { leftRings: 2, rightRings: 2 });
}

/* 16. Winding must not matter — the same square, wound the other way. */
expectSplit("square wound clockwise", [close([[0, 0], [0, 10], [10, 10], [10, 0]])],
            [-5, 5], [15, 5], { leftRings: 1, rightRings: 1 });

/* 17. Direction of the cut must not matter either: a→b and b→a swap the labels, nothing else. */
{
  const ab = splitRingsByLine([U], [-5, 6], [15, 6]);
  const ba = splitRingsByLine([U], [15, 6], [-5, 6]);
  check("cut direction only swaps the sides",
        ab.ok && ba.ok && ab.left.length === ba.right.length && ab.right.length === ba.left.length,
        ab.ok && ba.ok
          ? `${ab.left.length}/${ab.right.length} vs ${ba.left.length}/${ba.right.length}`
          : "refused");
}

/* 18. Real-world scale. The tolerance is relative to the cut's length, so a long cut across a
       small shape must still behave — this is the one that catches an absolute epsilon. */
expectSplit("long cut across a small shape",
            [close([[100, 100], [104, 100], [104, 104], [100, 104]])],
            [-5000, 102], [5000, 102], { leftRings: 1, rightRings: 1 });

/* ── verdict ──────────────────────────────────────────────────────────────── */

console.log(failures
  ? `\n${failures} of ${checks} checks FAILED`
  : `\n${checks} checks passed`);
process.exit(failures ? 1 : 0);
