// Generated by scripts/sync-ios-quick-access.mjs. Do not edit.
// Source: https://pointrmapstorage.blob.core.windows.net/taxonomy/10.12.0/taxonomy.json (10.12.0) joined with quick-access/aviation.json:
// each category's matched types' displayName and alsoKnownAs, and its service types.
import Foundation

enum QuickAccessTerms {
    static let version = "10.12.0"
    static let json = #"""
{
  "version": "10.12.0",
  "source": "https://pointrmapstorage.blob.core.windows.net/taxonomy/10.12.0/taxonomy.json",
  "categories": [
    {
      "name": "Entrances & Exits",
      "source": [
        "entrance-exit",
        "entrance-exit/entrance",
        "entrance-exit/exit"
      ],
      "phrases": [
        "access point (entry)",
        "building entrance",
        "building exit",
        "employee entrance",
        "employee exit",
        "entrance",
        "entrance - exit",
        "entrance - exits",
        "entrances & exits",
        "entry and exit",
        "exit",
        "exit door (labeled)",
        "garage exit",
        "lobby entrance",
        "main entrance",
        "main exit",
        "public entrance",
        "public exit",
        "side entrance",
        "side exit",
        "vip entrance"
      ]
    },
    {
      "name": "Check-in & Baggage",
      "source": [
        "service-space/office",
        "transportation-space/bag-drop-checkin",
        "transportation-space/baggage-reclaim",
        "service-space/desk",
        "amenity-space/desk"
      ],
      "phrases": [
        "airline check-in",
        "badge pickup",
        "bag drop",
        "bag drop / check-in",
        "bag drop / check-ins",
        "baggage claim",
        "baggage hall",
        "baggage pickup",
        "baggage reclaim",
        "baggage reclaims",
        "baggage services",
        "check-in & baggage",
        "check-in counter",
        "check-in desk",
        "luggage carousel",
        "travel and tourism"
      ]
    },
    {
      "name": "Security & Immigration",
      "source": [
        "security-space",
        "security-space/security-screening",
        "security-space/security-desk",
        "security-space/passport-control",
        "equipment/e-passport-gate",
        "section/customs-immigration"
      ],
      "phrases": [
        "abc gate",
        "automated border control",
        "automatic border gate",
        "baggage check",
        "biometric immigration gate",
        "body scan",
        "border control",
        "customs",
        "customs & immigration",
        "customs and border protection",
        "e-passport gate",
        "egates",
        "epassport gate",
        "guard desk",
        "immigration",
        "information desk",
        "passenger screening",
        "passport check",
        "passport control",
        "screening area",
        "security & immigration",
        "security & safety",
        "security desk",
        "security desks",
        "security office",
        "security screening",
        "security space",
        "security station",
        "x-ray screening"
      ]
    },
    {
      "name": "Gates",
      "source": [
        "transportation-space/boarding-gate",
        "service-space/office"
      ],
      "phrases": [
        "boarding gate",
        "flight gate",
        "gate",
        "gates",
        "travel and tourism"
      ]
    },
    {
      "name": "Customer Service",
      "source": [
        "amenity-space/desk",
        "amenity-space",
        "retail-space/personal-shopper-assist",
        "service-space",
        "retail-space/returns-desk",
        "equipment/information-display"
      ],
      "phrases": [
        "amenities",
        "amenity space",
        "announcement screen",
        "arrivals board",
        "badge pickup",
        "building amenities",
        "building facilities",
        "building services",
        "customer service",
        "departure board",
        "digital signage",
        "exchange desk",
        "facilities",
        "fashion consultant",
        "fids",
        "flight information display",
        "guest services",
        "help desk",
        "info board",
        "info display",
        "info screen",
        "information and help desk",
        "information display",
        "lost and found",
        "personal shopper assist",
        "personal shopper assistance",
        "professional services",
        "public display",
        "public services",
        "real-time display",
        "reception",
        "registration",
        "return services",
        "returns counter",
        "returns desk",
        "service space",
        "shopping assistant",
        "style advisor",
        "stylist service",
        "wayfinding screen"
      ]
    },
    {
      "name": "Parking & Ground Transport",
      "source": [
        "parking-space",
        "parking-space/electric-vehicle-station",
        "service-space/desk",
        "transportation-space/rideshare-pickup",
        "transportation-space/shuttle-station",
        "transportation-space/bus-station",
        "section/terminal",
        "parking-space/bike-rack",
        "transportation-space"
      ],
      "phrases": [
        "arrival hall",
        "bicycle rental",
        "bike rack",
        "bike share",
        "bike station",
        "bike stations",
        "bus station",
        "bus stop",
        "bus terminal",
        "car rental",
        "concourse",
        "departure hall",
        "domestic terminal",
        "electric vehicle station",
        "ev charger",
        "ev charging station",
        "ev charging stations",
        "hall",
        "international terminal",
        "parking & ground transport",
        "parking service",
        "parking services",
        "parking space",
        "passenger terminal",
        "rideshare pickup",
        "shuttle and transportation assistance",
        "shuttle bus stop",
        "shuttle pickup",
        "shuttle station",
        "shuttle stations",
        "station",
        "terminal",
        "terminals",
        "transit stop",
        "transportation service",
        "transportation services",
        "transportation space"
      ]
    },
    {
      "name": "Dining",
      "source": [
        "food-beverage-space",
        "food-beverage-space/bakery",
        "food-beverage-space/bar",
        "food-beverage-space/cafes-coffee-tea-houses",
        "food-beverage-space/cafeteria",
        "food-beverage-space/deli-buffet",
        "food-beverage-space/food-stall",
        "food-beverage-space/fast-food",
        "food-beverage-space/juice-smoothie-bar",
        "food-beverage-space/restaurant"
      ],
      "phrases": [
        "bakeries",
        "bakery",
        "bar",
        "bistro",
        "cafes",
        "cafes, coffee & tea houses",
        "cafeteria",
        "cafeterias",
        "coffee & tea houses",
        "deli / buffet",
        "deli / buffets",
        "diner",
        "dining",
        "drink stall",
        "eatery",
        "fast food",
        "fast foods",
        "festival stall",
        "food & beverage",
        "food & beverage space",
        "food & beverages",
        "food and drink stall",
        "food court stall",
        "food stall",
        "food vendor",
        "full-service restaurant",
        "hawker stall",
        "juice & smoothie bar",
        "juice & smoothie bars",
        "juice stand",
        "lounge",
        "market stall",
        "patisserie",
        "pub",
        "restaurant",
        "takeout",
        "tavern",
        "vendor stall"
      ]
    },
    {
      "name": "Shopping",
      "source": [
        "retail-space"
      ],
      "phrases": [
        "retail space",
        "retail spaces",
        "retail store",
        "shopping",
        "shopping area"
      ]
    },
    {
      "name": "Wellness & Spirituality",
      "source": [
        "faith-worship-space",
        "wellness-space",
        "decorative-environmental-feature/courtyard",
        "food-beverage-space/juice-smoothie-bar",
        "service-space/salon",
        "restroom-space/mothers-room"
      ],
      "phrases": [
        "atrium courtyard",
        "beauty and spa services",
        "breastfeeding room",
        "central courtyard",
        "courtyard",
        "enclosed garden",
        "faith & worship",
        "faith & worship space",
        "faith & worships",
        "feeding room",
        "garden courtyard",
        "health and wellness",
        "internal courtyard",
        "juice & smoothie bar",
        "juice & smoothie bars",
        "juice stand",
        "lactation room",
        "mothers' room",
        "mothers' rooms",
        "nursing room",
        "place of worship",
        "religious site",
        "wellness",
        "wellness & spirituality",
        "wellness space"
      ]
    },
    {
      "name": "Information & Help",
      "source": [
        "amenity-space/desk",
        "amenity-space",
        "equipment/information-display"
      ],
      "phrases": [
        "amenities",
        "amenity space",
        "announcement screen",
        "arrivals board",
        "badge pickup",
        "building amenities",
        "building facilities",
        "building services",
        "departure board",
        "digital signage",
        "facilities",
        "fids",
        "flight information display",
        "guest services",
        "info board",
        "info display",
        "info screen",
        "information & help",
        "information and help desk",
        "information display",
        "lost and found",
        "public display",
        "public services",
        "real-time display",
        "reception",
        "registration",
        "wayfinding screen"
      ]
    },
    {
      "name": "Restrooms",
      "source": [
        "restroom-space",
        "restroom-space/restroom",
        "restroom-space/baby-care-hygiene",
        "restroom-space/mothers-room",
        "restroom-space/changing-room",
        "restroom-space/shower",
        "restroom-space/locker-room"
      ],
      "phrases": [
        "baby care & hygiene",
        "baby care room",
        "baby changing station",
        "bathroom",
        "breastfeeding room",
        "changing room",
        "changing rooms",
        "diaper changing table",
        "dressing room",
        "feeding room",
        "fitting room",
        "lactation room",
        "lavatory",
        "locker room",
        "locker rooms",
        "loo",
        "mothers' room",
        "mothers' rooms",
        "nappy change",
        "nursery",
        "nursing room",
        "parent's room",
        "powder room",
        "restroom",
        "restroom facilities",
        "restroom space",
        "restrooms",
        "sanitary facilities",
        "shower",
        "shower facilities",
        "shower room",
        "showers",
        "toilet",
        "washroom",
        "wc"
      ]
    },
    {
      "name": "Accessible Places",
      "source": [
        "amenity-space/desk"
      ],
      "phrases": [
        "accessibility services",
        "accessible places"
      ]
    },
    {
      "name": "Vegan & Vegetarian",
      "source": [
        "food-beverage-space"
      ],
      "phrases": [
        "food & beverage",
        "food & beverage space",
        "food & beverages",
        "vegan & vegetarian"
      ]
    },
    {
      "name": "Anchor Stores",
      "source": [],
      "phrases": [
        "anchor stores"
      ]
    },
    {
      "name": "Kid-Friendly",
      "source": [
        "amenity-space/office",
        "activity-space/play-area",
        "medical-space/patient-room",
        "restroom-space/baby-care-hygiene"
      ],
      "phrases": [
        "baby care & hygiene",
        "baby care room",
        "baby changing station",
        "bed room",
        "childcare and daycare",
        "children's park",
        "diaper changing table",
        "hospital room",
        "inpatient room",
        "kid-friendly",
        "kids area",
        "nappy change",
        "nursery",
        "parent's room",
        "patient room",
        "play area",
        "play areas",
        "playground"
      ]
    },
    {
      "name": "Pet-Friendly",
      "source": [
        "amenity-space/pet-relief",
        "entertainment-space/wildlife-exhibit",
        "medical-space/veterinary-clinic"
      ],
      "phrases": [
        "animal clinic",
        "animal exhibit",
        "aquarium",
        "fish house",
        "marine exhibit",
        "pet relief",
        "pet-friendly",
        "petting zoo",
        "reptile exhibit",
        "veterinary clinic",
        "veterinary clinics",
        "wildlife exhibit",
        "wildlife sanctuary",
        "zoo"
      ]
    }
  ]
}
"""#
}
