name: "Visual Regression Testing"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Chromatic requires full git history

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build dependencies
        run: pnpm --filter '!@kozmos/docs' build # Build everything except docs/storybook to save time; Chromatic will build Storybook.

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          # 👇 Chromatic token is required. Ensure you add it to GitHub Secrets.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # The storybook is located in apps/docs
          workingDir: apps/docs
          buildScriptName: build-storybook
